import { FlowchartData } from "./FlowchartAnimation";

export const SECURITY_FLOWCHARTS: FlowchartData[] = [
  {
    id: "sec-rate-limiting-flow",
    title: "Multi-Layer Rate Limiting & DDoS Defense",
    subtitle: "Edge → CDN → WAF → Application → Database — Defense in Depth",
    nodes: [
      {
        id: "internet",
        label: "Internet\n(Attackers + Users)",
        x: 710,
        y: 120,
        width: 500,
        height: 70,
        type: "start",
      },
      {
        id: "edge",
        label: "Layer 1: Edge\nCloudflare/AWS Shield",
        x: 735,
        y: 260,
        width: 450,
        height: 70,
        type: "process",
      },
      {
        id: "waf",
        label: "Layer 2: WAF\nModSecurity / AWS WAF",
        x: 735,
        y: 400,
        width: 450,
        height: 70,
        type: "process",
      },
      {
        id: "app",
        label: "Layer 3: App\nToken Bucket / Redis",
        x: 735,
        y: 540,
        width: 450,
        height: 70,
        type: "process",
      },
      {
        id: "decision",
        label: "Flash Crowd\nor Botnet?",
        x: 760,
        y: 670,
        width: 400,
        height: 100,
        type: "decision",
      },
      {
        id: "allow",
        label: "✅ Allow\nLegitimate traffic",
        x: 610,
        y: 840,
        width: 250,
        height: 70,
        type: "end",
      },
      {
        id: "block",
        label: "❌ Block\n429 / CAPTCHA / Drop",
        x: 1060,
        y: 840,
        width: 250,
        height: 70,
        type: "end",
      },
    ],
    edges: [
      {
        from: "internet",
        to: "edge",
        label: "All traffic",
        path: "M 960 190 L 960 260",
      },
      {
        from: "edge",
        to: "waf",
        label: "SYN cookies, rate limit",
        path: "M 960 330 L 960 400",
      },
      {
        from: "waf",
        to: "app",
        label: "SQLi/XSS filtered",
        path: "M 960 470 L 960 540",
      },
      {
        from: "app",
        to: "decision",
        label: "Token bucket check",
        path: "M 960 610 L 960 670",
      },
      {
        from: "decision",
        to: "allow",
        label: "Tokens available",
        path: "M 800 720 L 735 840",
      },
      {
        from: "decision",
        to: "block",
        label: "Rate exceeded / bot",
        path: "M 1120 720 L 1185 840",
      },
    ],
    durationInFrames: 300,
  },
  {
    id: "sec-supply-chain-flow",
    title: "Software Supply Chain Security Pipeline",
    subtitle: "Developer → VCS → CI/CD → Registry → Production — Signed & Verified",
    nodes: [
      {
        id: "dev",
        label: "Developer\nSigned Commit (GPG)",
        x: 760,
        y: 120,
        width: 400,
        height: 70,
        type: "start",
      },
      {
        id: "vcs",
        label: "Version Control\nGitHub / GitLab",
        x: 760,
        y: 260,
        width: 400,
        height: 70,
        type: "process",
      },
      {
        id: "scan",
        label: "Dependency Scan\nTrivy + Grype + Dependabot",
        x: 760,
        y: 400,
        width: 400,
        height: 70,
        type: "process",
      },
      {
        id: "build",
        label: "Build & SBOM\nSyft + CycloneDX/SPDX",
        x: 760,
        y: 540,
        width: 400,
        height: 70,
        type: "process",
      },
      {
        id: "sign",
        label: "Container Signing\nCosign + Sigstore",
        x: 760,
        y: 680,
        width: 400,
        height: 70,
        type: "process",
      },
      {
        id: "deploy",
        label: "🚀 Deploy to Production\nAdmission Control (Kyverno)",
        x: 760,
        y: 820,
        width: 400,
        height: 70,
        type: "end",
      },
    ],
    edges: [
      {
        from: "dev",
        to: "vcs",
        label: "git commit -S",
        path: "M 960 190 L 960 260",
      },
      {
        from: "vcs",
        to: "scan",
        label: "PR opened / push",
        path: "M 960 330 L 960 400",
      },
      {
        from: "scan",
        to: "build",
        label: "No critical CVEs",
        path: "M 960 470 L 960 540",
      },
      {
        from: "build",
        to: "sign",
        label: "SBOM generated",
        path: "M 960 610 L 960 680",
      },
      {
        from: "sign",
        to: "deploy",
        label: "Image verified",
        path: "M 960 750 L 960 820",
      },
    ],
    durationInFrames: 240,
  },
  {
    id: "sec-cors-flow",
    title: "CORS Preflight & Cross-Origin Request Flow",
    subtitle: "Browser → Preflight (OPTIONS) → Server Response → Actual Request",
    nodes: [
      {
        id: "frontend",
        label: "Frontend\napp.newdomain.com",
        x: 750,
        y: 120,
        width: 420,
        height: 70,
        type: "start",
      },
      {
        id: "preflight",
        label: "Preflight Request\nOPTIONS /api/transfer",
        x: 750,
        y: 270,
        width: 420,
        height: 70,
        type: "process",
      },
      {
        id: "server",
        label: "Backend Response\nAccess-Control-Allow-*",
        x: 750,
        y: 420,
        width: 420,
        height: 70,
        type: "process",
      },
      {
        id: "decision-cors",
        label: "Origin Allowed?\ncheck Origin header",
        x: 770,
        y: 560,
        width: 380,
        height: 100,
        type: "decision",
      },
      {
        id: "actual",
        label: "✅ Actual Request\nPOST with credentials",
        x: 580,
        y: 740,
        width: 280,
        height: 70,
        type: "end",
      },
      {
        id: "blocked",
        label: "❌ Request Blocked\nCORS error in browser",
        x: 1060,
        y: 740,
        width: 280,
        height: 70,
        type: "end",
      },
    ],
    edges: [
      {
        from: "frontend",
        to: "preflight",
        label: "Cross-origin request",
        path: "M 960 190 L 960 270",
      },
      {
        from: "preflight",
        to: "server",
        label: "Origin: newdomain.com",
        path: "M 960 340 L 960 420",
      },
      {
        from: "server",
        to: "decision-cors",
        label: "Allow-Credentials: true",
        path: "M 960 490 L 960 560",
      },
      {
        from: "decision-cors",
        to: "actual",
        label: "✅ Origin whitelisted",
        path: "M 840 610 L 720 740",
      },
      {
        from: "decision-cors",
        to: "blocked",
        label: "⛔ Origin not allowed",
        path: "M 1080 610 L 1200 740",
      },
    ],
    durationInFrames: 270,
  },
];
