import { SequenceData } from "./SequenceDiagram";

export const ADVANCED_SEQUENCES: SequenceData[] = [
  // ═══════════════════════════════════════════════════════════
  // CI/CD DEPLOYMENT (6 sequences)
  // ═══════════════════════════════════════════════════════════

  {
    id: "cicd-end-to-end-pipeline",
    title: "CI/CD Pipeline — End to End",
    subtitle: "Code → Commit → CI (Test) → Build (Artifact) → CD (Promote) → Production (Serve)",
    actors: ["Developer", "Git Repo", "CI Runner", "Artifact Registry", "Kubernetes"],
    steps: [
      { from: 0, to: 1, label: "git push origin main", detail: "Commit abc1234" },
      { from: 1, to: 2, label: "Push webhook trigger", detail: "GitHub Actions / GitLab CI" },
      { from: 2, to: 2, label: "Run tests + lint", detail: "pytest, ruff, type-check" },
      { from: 2, to: 3, label: "docker build & push", detail: "Image: myapp:abc1234" },
      { from: 3, to: 4, label: "kubectl set image", detail: "Update deployment manifest" },
      { from: 4, to: 4, label: "Rolling update", detail: "Health checks → Ready → Serve" },
      { from: 4, to: 0, label: "✅ Deployed!", detail: "Production serving new code" },
    ],
    durationInFrames: 240,
  },
  {
    id: "cicd-blue-green-deployment",
    title: "Blue-Green Deployment",
    subtitle: "Two identical environments — instant switch, instant rollback",
    actors: ["Load Balancer", "Blue (v1 — Active)", "Green (v2 — Idle)", "Monitoring"],
    steps: [
      { from: 0, to: 1, label: "Serve all traffic", detail: "Blue = current production" },
      { from: 1, to: 3, label: "Metrics: healthy", detail: "P99 latency < 200ms" },
      { from: 2, to: 2, label: "Deploy v2 to Green", detail: "Same infra, new image" },
      { from: 2, to: 3, label: "Smoke tests pass", detail: "Green validated" },
      { from: 3, to: 0, label: "Green healthy ✅", detail: "Ready to switch" },
      { from: 0, to: 2, label: "Switch traffic → Green", detail: "Update LB target group" },
      { from: 2, to: 0, label: "Serving v2", detail: "Green = active" },
      { from: 1, to: 0, label: "Blue drained", detail: "Standby for instant rollback" },
    ],
    durationInFrames: 270,
  },
  {
    id: "cicd-canary-release",
    title: "Canary Release",
    subtitle: "Progressive traffic shift: 5% → 25% → 50% → 100% with metric gates",
    actors: ["Load Balancer", "Old Version (v1)", "New Version (v2)", "Observability"],
    steps: [
      { from: 0, to: 1, label: "95% traffic", detail: "v1 serves majority" },
      { from: 0, to: 2, label: "5% traffic (canary)", detail: "v2 gets subset of users" },
      { from: 2, to: 3, label: "Metrics: healthy", detail: "Error rate < 0.1%" },
      { from: 3, to: 0, label: "Canary OK ✅ → 25%", detail: "Increase canary weight" },
      { from: 0, to: 2, label: "25% traffic", detail: "Monitor for 5 min" },
      { from: 2, to: 3, label: "Latency: baseline", detail: "P99 within threshold" },
      { from: 3, to: 0, label: "Canary OK ✅ → 50%", detail: "Gradual increase" },
      { from: 0, to: 2, label: "50% traffic", detail: "Half of users on v2" },
      { from: 2, to: 3, label: "All metrics green", detail: "No degradation detected" },
      { from: 3, to: 0, label: "Promote to 100% ✅", detail: "v2 = new production" },
      { from: 0, to: 1, label: "v1 scaled down", detail: "Old version removed" },
    ],
    durationInFrames: 360,
  },
  {
    id: "cicd-artifact-promotion",
    title: "Artifact Promotion Pipeline",
    subtitle: "Same binary promoted through environments with validation gates",
    actors: ["Commit", "Dev / Staging", "Canary", "Production"],
    steps: [
      { from: 0, to: 1, label: "Build: myapp:abc1234", detail: "Single immutable artifact" },
      { from: 1, to: 1, label: "Auto-deploy on merge", detail: "Unit + integration tests" },
      { from: 1, to: 2, label: "Smoke tests pass", detail: "E2E test suite" },
      { from: 2, to: 2, label: "5% traffic canary", detail: "Metrics + error budget check" },
      { from: 2, to: 3, label: "Performance OK ✅", detail: "Manual approval gate" },
      { from: 3, to: 3, label: "100% rollout", detail: "Monitor alert thresholds" },
    ],
    durationInFrames: 210,
  },
  {
    id: "cicd-frontend-pipeline",
    title: "Frontend Deployment Pipeline",
    subtitle: "React / Next.js — Code Push → CI → Build → CDN → Cache Invalidation",
    actors: ["Developer", "GitHub", "CI (Actions)", "S3 / CDN"],
    steps: [
      { from: 0, to: 1, label: "git push feat/dark-mode", detail: "New feature branch" },
      { from: 1, to: 2, label: "Push webhook", detail: "PR #123 created" },
      { from: 2, to: 2, label: "npm ci + lint + test", detail: "Frozen lockfile" },
      { from: 2, to: 2, label: "npm run build", detail: "Produces dist/ with hashed files" },
      { from: 2, to: 3, label: "Upload to S3", detail: "dist/ → s3://app-bucket" },
      { from: 3, to: 3, label: "Invalidate CloudFront", detail: "CDN cache purged" },
      { from: 3, to: 0, label: "✅ Dark mode live!", detail: "Served via CDN edge" },
    ],
    durationInFrames: 240,
  },
  {
    id: "cicd-backend-pipeline",
    title: "Backend Deployment Pipeline",
    subtitle: "Dockerized service — Code → Build → Push → Deploy → Rolling Update",
    actors: ["Developer", "GitHub", "CI (Build + Test)", "ECR (Registry)", "Kubernetes"],
    steps: [
      { from: 0, to: 1, label: "git push main", detail: "Backend service update" },
      { from: 1, to: 2, label: "Webhook trigger", detail: "GitHub Actions workflow" },
      { from: 2, to: 2, label: "Run tests", detail: "Unit + integration + lint" },
      { from: 2, to: 3, label: "Docker build & push", detail: "myapp:abc1234" },
      { from: 3, to: 4, label: "kubectl set image", detail: "Update deployment" },
      { from: 4, to: 4, label: "Rolling update", detail: "New pod → Ready → Old pod drained" },
      { from: 4, to: 0, label: "✅ Service updated!", detail: "Zero-downtime deploy" },
    ],
    durationInFrames: 240,
  },

  // ═══════════════════════════════════════════════════════════
  // KUBERNETES (3 sequences)
  // ═══════════════════════════════════════════════════════════

  {
    id: "k8s-pod-lifecycle",
    title: "Pod Lifecycle State Machine",
    subtitle: "Pending → Running → Succeeded / Failed — with container states",
    actors: ["kubectl apply", "Scheduler", "kubelet", "Container Runtime"],
    steps: [
      { from: 0, to: 1, label: "Pod YAML submitted", detail: "Phase: Pending" },
      { from: 1, to: 1, label: "Filter & score nodes", detail: "Taints, affinity, resources" },
      { from: 1, to: 2, label: "Assigned to node-3", detail: "Phase: Pending → Scheduled" },
      { from: 2, to: 3, label: "Pull image", detail: "Container state: Waiting" },
      { from: 3, to: 2, label: "Image pulled", detail: "Container state: Running" },
      { from: 2, to: 0, label: "Phase: Running", detail: "READY 1/1, serving traffic" },
      { from: 2, to: 3, label: "Probe: liveness fails", detail: "Restart count +1" },
      { from: 3, to: 2, label: "Container restarted", detail: "CrashLoopBackOff if repeated" },
      { from: 2, to: 0, label: "Phase: Succeeded", detail: "Exit code: 0 (job complete)" },
    ],
    durationInFrames: 300,
  },
  {
    id: "k8s-container-states",
    title: "Container States Deep Dive",
    subtitle: "Waiting → Running → Terminated — with common failure reasons",
    actors: ["Container", "Image Pull", "Process", "Health Probe"],
    steps: [
      { from: 0, to: 1, label: "State: Waiting", detail: "Reason: ContainerCreating" },
      { from: 1, to: 0, label: "Image downloaded", detail: "sha256:abc...def" },
      { from: 0, to: 2, label: "State: Running", detail: "PID 1 started in container" },
      { from: 2, to: 3, label: "Liveness probe: /health", detail: "HTTP 200 OK" },
      { from: 3, to: 2, label: "Probe passing", detail: "Container stays alive" },
      { from: 2, to: 2, label: "OOM: exceeds memory limit", detail: "Exit code: 137 (SIGKILL)" },
      { from: 2, to: 0, label: "State: Terminated", detail: "Reason: OOMKilled" },
      { from: 0, to: 2, label: "Restart: backoff 10s", detail: "CrashLoopBackOff progression" },
    ],
    durationInFrames: 270,
  },
  {
    id: "k8s-monitoring-stack",
    title: "Kubernetes Monitoring Stack",
    subtitle: "kubelet → cAdvisor → Metrics Server → HPA / kubectl top",
    actors: ["kubelet", "cAdvisor", "Metrics Server", "HPA / kubectl top"],
    steps: [
      { from: 0, to: 1, label: "Collect container stats", detail: "10s interval" },
      { from: 1, to: 2, label: "Serve /metrics/resource", detail: "CPU + Memory summary" },
      { from: 2, to: 2, label: "Aggregate across nodes", detail: "60s resolution" },
      { from: 2, to: 3, label: "Resource Metrics API", detail: "Used by HPA + kubectl top" },
      { from: 3, to: 3, label: "kubectl top pods", detail: "CPU: 125m, Memory: 456Mi" },
      { from: 1, to: 0, label: "Detailed metrics", detail: "container_memory_working_set" },
    ],
    durationInFrames: 210,
  },

  // ═══════════════════════════════════════════════════════════
  // COMPUTER NETWORKS (3 sequences)
  // ═══════════════════════════════════════════════════════════

  {
    id: "net-tls-handshake",
    title: "TLS 1.3 Handshake",
    subtitle: "1-RTT handshake with pre-shared key for 0-RTT resumption",
    actors: ["Client (Browser)", "TLS 1.3 Server"],
    steps: [
      { from: 0, to: 1, label: "ClientHello + KeyShare", detail: "X25519 public key included" },
      { from: 1, to: 0, label: "ServerHello + KeyShare", detail: "Server's ECDHE public key" },
      { from: 1, to: 0, label: "EncryptedExtensions", detail: "Server parameters (ALPN, etc)" },
      { from: 1, to: 0, label: "Certificate + Verify", detail: "Ed25519 signature (~40µs)" },
      { from: 1, to: 0, label: "Finished (1 RTT)", detail: "Handshake complete!" },
      { from: 0, to: 1, label: "Finished + HTTP Request", detail: "Application data starts" },
      { from: 1, to: 0, label: "HTTP Response", detail: "Data at RTT 2 (vs RTT 3 for TLS 1.2)" },
    ],
    durationInFrames: 210,
  },
  {
    id: "net-dns-resolution",
    title: "DNS Resolution Deep Dive",
    subtitle: "Browser → Stub → Root → TLD → Authoritative → IP Address",
    actors: ["Browser", "Stub Resolver", "Root Server", "TLD Server", "Authoritative NS"],
    steps: [
      { from: 0, to: 1, label: "Check local cache", detail: "nscd / systemd-resolved" },
      { from: 0, to: 1, label: "nslookup example.com", detail: "Cache MISS — query upstream" },
      { from: 1, to: 2, label: "Where is .com?", detail: "Recursive query starts" },
      { from: 2, to: 1, label: "Ask .com TLD server", detail: "a.gtld-servers.net" },
      { from: 1, to: 3, label: "Where is example.com?", detail: "Query TLD server" },
      { from: 3, to: 1, label: "Ask ns1.example.com", detail: "Authoritative nameservers" },
      { from: 1, to: 4, label: "example.com A record?", detail: "Final authoritative query" },
      { from: 4, to: 1, label: "IN A 203.0.113.10", detail: "TTL: 300 seconds" },
      { from: 1, to: 0, label: "203.0.113.10 ✓", detail: "Browser opens TCP connection" },
    ],
    durationInFrames: 270,
  },
  {
    id: "net-http2-vs-quic",
    title: "HTTP/2 vs HTTP/3 (QUIC)",
    subtitle: "One lost packet: H2 blocks ALL streams, QUIC only blocks one",
    actors: ["Client (H2)", "TCP Connection", "Client (QUIC)"],
    steps: [
      { from: 0, to: 1, label: "Stream 1 (CSS)", detail: "Request sent" },
      { from: 0, to: 1, label: "Stream 2 (JS)", detail: "Request sent" },
      { from: 0, to: 1, label: "Stream 3 (IMG)", detail: "⚠️ PACKET LOST!" },
      { from: 0, to: 1, label: "Stream 4 (FONT)", detail: "❌ BLOCKED — TCP HoL" },
      { from: 1, to: 0, label: "Stream 1 delivered", detail: "CSS received" },
      { from: 1, to: 0, label: "Stream 2 delivered", detail: "JS received" },
      { from: 1, to: 0, label: "Rest waiting...", detail: "Until retransmit completes" },
      { from: 0, to: 2, label: "Stream 5 (CSS) QUIC", detail: "Sent via independent stream" },
      { from: 0, to: 2, label: "Stream 6 (IMG) ⚠️", detail: "Lost — only Stream 6 blocked" },
      { from: 0, to: 2, label: "Stream 7 (FONT) ✅", detail: "NOT blocked! Delivered!" },
      { from: 2, to: 0, label: "H3 wins at 3% loss", detail: "66% faster than H2 on lossy links" },
    ],
    durationInFrames: 330,
  },

  // ═══════════════════════════════════════════════════════════
  // DISTRIBUTED SYSTEMS (4 sequences)
  // ═══════════════════════════════════════════════════════════

  {
    id: "ds-raft-leader-election",
    title: "Raft Leader Election",
    subtitle: "Leader fails → randomized timeouts → term increment → majority vote → new leader",
    actors: ["Node 1 (Leader)", "Node 2 (Follower)", "Node 3 (Follower)"],
    steps: [
      { from: 0, to: 1, label: "Heartbeat (term 3)", detail: "Every 50ms" },
      { from: 0, to: 2, label: "Heartbeat (term 3)", detail: "Followers reset timer" },
      { from: 0, to: 0, label: "⚠️ Node 1 CRASHES", detail: "No more heartbeats" },
      { from: 1, to: 1, label: "Election timeout (180ms)", detail: "Term: 3 → 4" },
      { from: 1, to: 2, label: "RequestVote (term 4)", detail: "lastLogIndex: 3, term: 3" },
      { from: 2, to: 1, label: "Vote granted", detail: "Log is up-to-date ✓" },
      { from: 1, to: 1, label: "2/3 votes → LEADER!", detail: "Term 4, sending heartbeats" },
      { from: 1, to: 0, label: "Heartbeat (term 4)", detail: "Node 1 recovers → steps down" },
      { from: 1, to: 2, label: "Heartbeat (term 4)", detail: "Stable leader established" },
    ],
    durationInFrames: 300,
  },
  {
    id: "ds-twopc-vs-saga",
    title: "2PC vs Saga Pattern",
    subtitle: "Coordinator failure blocks 2PC — Saga's compensating actions save the day",
    actors: ["Coordinator", "Inventory Service", "Payment Service", "Shipping Service"],
    steps: [
      { from: 0, to: 1, label: "Prepare: Reserve stock", detail: "Row LOCKED" },
      { from: 0, to: 2, label: "Prepare: Authorize payment", detail: "Hold placed" },
      { from: 0, to: 3, label: "Prepare: Create label", detail: "Pre-generated" },
      { from: 1, to: 0, label: "Prepared ✓", detail: "⚠️ Resource locked!" },
      { from: 2, to: 0, label: "Prepared ✓", detail: "⚠️ Payment held!" },
      { from: 0, to: 0, label: "⛔ Coordinator CRASHES!", detail: "ALL participants BLOCKED" },
      { from: 1, to: 1, label: "Locked indefinitely", detail: "2PC blocking problem" },
      { from: 0, to: 1, label: "SAGA: Reserve stock", detail: "Local TX — release lock" },
      { from: 0, to: 2, label: "SAGA: Charge card", detail: "Local TX, immediate commit" },
      { from: 2, to: 2, label: "Payment FAILED", detail: "Insufficient funds" },
      { from: 0, to: 1, label: "Compensate: Release stock", detail: "Business refund action" },
      { from: 1, to: 0, label: "Stock released ✓", detail: "All compensated cleanly" },
    ],
    durationInFrames: 360,
  },
  {
    id: "ds-consistent-hashing",
    title: "Consistent Hashing on a Ring",
    subtitle: "O(1/N) key redistribution vs O(1) — virtual nodes balance load",
    actors: ["Key X (hash=42)", "Node A (hash=10)", "Node B (hash=70)", "Node C (hash=150)"],
    steps: [
      { from: 0, to: 1, label: "hash(X) = 42", detail: "Lookup on ring" },
      { from: 1, to: 0, label: "Walk clockwise", detail: "Next node after position 42" },
      { from: 0, to: 2, label: "Node B owns key X!", detail: "Store X on Node B" },
      { from: 2, to: 2, label: "Node B FAILS ⚠️", detail: "Only keys in [70→A] move" },
      { from: 0, to: 3, label: "Reassigned to Node C", detail: "Only 1/N keys move (~2%)" },
      { from: 2, to: 1, label: "Virtual nodes (×200)", detail: "Near-uniform load distribution" },
    ],
    durationInFrames: 210,
  },
  {
    id: "ds-swim-gossip",
    title: "SWIM Gossip Protocol",
    subtitle: "Ping → Indirect Probe → Suspect → Dead — failure detection at scale",
    actors: ["Node A (Pinger)", "Node B (Target)", "Node C (Helper)"],
    steps: [
      { from: 0, to: 1, label: "PING", detail: "Direct probe — 100ms timeout" },
      { from: 1, to: 1, label: "⚠️ Packet dropped", detail: "A gets no ACK" },
      { from: 0, to: 2, label: "PING_REQ: probe B", detail: "Indirect probe via C" },
      { from: 2, to: 1, label: "PING (from C)", detail: "Different network path" },
      { from: 1, to: 2, label: "ACK", detail: "B is alive!" },
      { from: 2, to: 0, label: "B is ALIVE ✅", detail: "False positive avoided" },
      { from: 0, to: 1, label: "PING (next cycle)", detail: "Now also timeout" },
      { from: 0, to: 2, label: "PING_REQ: probe B", detail: "K=3 indirect attempts" },
      { from: 2, to: 0, label: "B unreachable ❌", detail: "Mark SUSPECT → DEAD" },
      { from: 0, to: 2, label: "Gossip: B is DEAD", detail: "O(log N) rounds to converge" },
    ],
    durationInFrames: 300,
  },

  // ═══════════════════════════════════════════════════════════
  // SOFTWARE ARCHITECTURE (3 sequences)
  // ═══════════════════════════════════════════════════════════

  {
    id: "arch-cqrs-event-sourcing",
    title: "CQRS + Event Sourcing",
    subtitle: "Command → Aggregate → Event Store → Projector → Materialized View → Query",
    actors: ["Client", "Command Handler", "Event Store", "Projector", "Query Handler"],
    steps: [
      { from: 0, to: 1, label: "Transfer $100: A→B", detail: "Command issued" },
      { from: 1, to: 1, label: "Validate: balance OK", detail: "Business rules checked" },
      { from: 1, to: 2, label: "Append: Debited+Credited", detail: "Immutable event log" },
      { from: 2, to: 1, label: "Stored at offset 42", detail: "Events persisted" },
      { from: 1, to: 0, label: "⏳ Transfer accepted", detail: "Eventual consistency" },
      { from: 2, to: 3, label: "Stream new events", detail: "Kafka event bus" },
      { from: 3, to: 4, label: "Update materialized view", detail: "Rebuild balance snapshot" },
      { from: 4, to: 0, label: "✅ Balance: $900", detail: "Read-your-write after projection" },
      { from: 2, to: 2, label: "Replay from start", detail: "Rebuild full state" },
    ],
    durationInFrames: 270,
  },
  {
    id: "arch-circuit-breaker",
    title: "Circuit Breaker Pattern",
    subtitle: "Closed → Open → Half-Open — protecting services from cascading failures",
    actors: ["Client", "Circuit Breaker", "Upstream Service"],
    steps: [
      { from: 0, to: 1, label: "Request /api/data", detail: "State: CLOSED" },
      { from: 1, to: 2, label: "Forward request", detail: "Pass-through allowed" },
      { from: 2, to: 1, label: "200 OK", detail: "Success: counter reset" },
      { from: 1, to: 0, label: "Response delivered", detail: "Normal operation" },
      { from: 0, to: 1, label: "Request (×5)", detail: "5 consecutive failures" },
      { from: 1, to: 2, label: "GET /api/data", detail: "Returns 500 Server Error" },
      { from: 2, to: 1, label: "❌ 5th failure!", detail: "Threshold: 5 in 10s window" },
      { from: 1, to: 1, label: "State → OPEN", detail: "Reject immediately" },
      { from: 0, to: 1, label: "Request /api/data", detail: "Circuit OPEN" },
      { from: 1, to: 0, label: "❌ FAIL FAST", detail: "Return cached/fallback" },
      { from: 1, to: 1, label: "Timeout (30s elapsed)", detail: "State → HALF-OPEN" },
      { from: 1, to: 2, label: "Probe request (1 only)", detail: "Test if service recovered" },
      { from: 2, to: 1, label: "200 OK ✅", detail: "Service healthy again" },
      { from: 1, to: 1, label: "State → CLOSED", detail: "Resume normal operation" },
    ],
    durationInFrames: 390,
  },
  {
    id: "arch-microservices-decomposition",
    title: "Microservices Decomposition (DDD)",
    subtitle: "Monolith → Bounded Contexts → Independent Services with Anti-Corruption Layer",
    actors: ["Monolith", "Identity Bounded Ctx", "Orders Bounded Ctx", "Shipping Bounded Ctx", "Anti-Corruption Layer"],
    steps: [
      { from: 0, to: 0, label: "E-commerce monolith", detail: "Auth, Catalog, Orders, Shipping" },
      { from: 0, to: 1, label: "Extract: Identity & Auth", detail: "User registration, login, roles" },
      { from: 0, to: 2, label: "Extract: Orders", detail: "Order placement, fulfillment" },
      { from: 0, to: 3, label: "Extract: Shipping", detail: "Labels, tracking, carriers" },
      { from: 2, to: 4, label: "Get user address", detail: "ACL translates context language" },
      { from: 4, to: 1, label: "UserUpdated event", detail: "Event-sourced local copy" },
      { from: 1, to: 4, label: "Address: 123 Main St", detail: "Identity is source of truth" },
      { from: 4, to: 2, label: "shipping_address: ...", detail: "Translated to Orders language" },
      { from: 2, to: 0, label: "Monolith decommissioned", detail: "All contexts extracted ✓" },
    ],
    durationInFrames: 300,
  },

  // ═══════════════════════════════════════════════════════════
  // AWS — VPC & NETWORKING (2 sequences)
  // ═══════════════════════════════════════════════════════════

  {
    id: "aws-vpc-peering-vs-tgw",
    title: "VPC Peering vs Transit Gateway",
    subtitle: "1:1 peering vs hub-and-spoke — transitive routing & N×N complexity comparison",
    actors: ["VPC A (Spoke)", "VPC Peering (1:1)", "Transit Gateway", "VPC C (Spoke)"],
    steps: [
      { from: 0, to: 1, label: "Create peering request", detail: "A→B direct, no routing yet" },
      { from: 1, to: 1, label: "Accept + add route", detail: "Route: 10.1.0.0/16 → peering" },
      { from: 1, to: 0, label: "✅ A↔B connected", detail: "Direct 1:1 connection" },
      { from: 0, to: 2, label: "Create TGW attachment", detail: "Hub-and-spoke: VPC attach" },
      { from: 2, to: 0, label: "✅ Attachment active", detail: "Single connection to hub" },
      { from: 0, to: 1, label: "Route to VPC C?", detail: "❌ No transitive routing!" },
      { from: 1, to: 0, label: "A→C BLOCKED ⛔", detail: "Peering = non-transitive" },
      { from: 2, to: 3, label: "VPC C attached", detail: "TGW route table: all VPCs" },
      { from: 2, to: 0, label: "A↔C via TGW ✅", detail: "Transitive routing works!" },
      { from: 0, to: 1, label: "100 VPCs → 4950 peerings", detail: "N×(N-1)/2 complexity ❌" },
      { from: 2, to: 0, label: "100 VPCs → 100 attach", detail: "Linear scaling ✅ 74% cheaper" },
    ],
    durationInFrames: 330,
  },

  {
    id: "aws-route53-dns-routing",
    title: "Route53 Multi-Region DNS Routing",
    subtitle: "Latency-based routing with health checks and automatic failover across 3 regions",
    actors: ["Global User", "Route53 DNS", "us-east-1 (Primary)", "eu-west-1 (DR)", "ap-southeast-1"],
    steps: [
      { from: 0, to: 1, label: "DNS: saas.example.com", detail: "Stub resolver → Route53" },
      { from: 1, to: 1, label: "Latency evaluation", detail: "us-east-1: 30ms, eu-west: 150ms" },
      { from: 1, to: 2, label: "ALIAS → alb-us-east-1", detail: "Latency-based: closest region" },
      { from: 2, to: 0, label: "200 OK (30ms)", detail: "User served by primary region" },
      { from: 1, to: 2, label: "Health check: GET /health", detail: "⚠️ 3 consecutive failures" },
      { from: 2, to: 1, label: "HTTP 503 (×3)", detail: "Region marked UNHEALTHY" },
      { from: 1, to: 1, label: "Detection: 30s elapsed", detail: "Failover initiated" },
      { from: 1, to: 3, label: "ALIAS → alb-eu-west-1", detail: "TTL: 60s (DNS cached 60s)" },
      { from: 3, to: 0, label: "200 OK (150ms)", detail: "Total failover: ~90s" },
      { from: 1, to: 2, label: "Health check passes", detail: "Primary region recovered" },
      { from: 1, to: 0, label: "Route back to us-east-1", detail: "Latency-based: restored" },
    ],
    durationInFrames: 330,
  },

  // ═══════════════════════════════════════════════════════════
  // AWS — STORAGE & DATABASE (1 sequence)
  // ═══════════════════════════════════════════════════════════

  {
    id: "aws-s3-consistency",
    title: "S3 Strong Consistency Model",
    subtitle: "Read-after-write, strong deletes, and the only eventual holdout — LIST operations",
    actors: ["Client", "S3 (Primary)", "S3 (Replica / CRR)"],
    steps: [
      { from: 0, to: 1, label: "PUT /data.txt", detail: "New object (POST, Dec 2020+)" },
      { from: 1, to: 0, label: "HTTP 200", detail: "Write acknowledged" },
      { from: 0, to: 1, label: "GET /data.txt (immediate)", detail: "Strong read-after-write ✅" },
      { from: 1, to: 0, label: "200 → returns object", detail: "Never stale!" },
      { from: 0, to: 1, label: "DELETE /data.txt", detail: "Delete operation" },
      { from: 1, to: 0, label: "204 No Content", detail: "Delete acknowledged" },
      { from: 0, to: 1, label: "GET /data.txt", detail: "Immediate read after delete" },
      { from: 1, to: 0, label: "404 Not Found ✅", detail: "Strong delete consistency" },
      { from: 0, to: 1, label: "LIST bucket", detail: "Only eventual operation" },
      { from: 1, to: 0, label: "⚠️ May still show deleted", detail: "LIST is eventually consistent" },
      { from: 1, to: 2, label: "CRR: replicate to DR", detail: "S3 RTC: < 15 min SLA" },
      { from: 2, to: 0, label: "Replica available ✅", detail: "Cross-region replicated" },
    ],
    durationInFrames: 360,
  },

  // ═══════════════════════════════════════════════════════════
  // AWS — COMPUTE / LAMBDA (1 sequence)
  // ═══════════════════════════════════════════════════════════

  {
    id: "aws-lambda-lifecycle",
    title: "Lambda Cold Start & Execution Lifecycle",
    subtitle: "Download → Firecracker MicroVM → Runtime Init → Handler Code → Warm Reuse",
    actors: ["Invocation", "Lambda Service", "Firecracker MicroVM", "Language Runtime", "Handler Code"],
    steps: [
      { from: 0, to: 1, label: "First invocation", detail: "⏳ Cold start begins" },
      { from: 1, to: 2, label: "Download code from S3", detail: "Unzip to /var/task (~50ms)" },
      { from: 2, to: 2, label: "Create Firecracker µVM", detail: "KVM-based sandbox (~50ms)" },
      { from: 2, to: 1, label: "Assign ENI (VPC only)", detail: "Hyperplane pre-warms: ~50ms" },
      { from: 1, to: 3, label: "Configure IAM creds", detail: "STS AssumeRole (env vars)" },
      { from: 3, to: 3, label: "Import all modules", detail: "Python: 100-500ms, Java: 1-5s" },
      { from: 3, to: 4, label: "Run global init code", detail: "DB connections, HTTP clients" },
      { from: 4, to: 0, label: "Execute handler fn ✅", detail: "Cold start: ~200ms (no VPC)" },
      { from: 0, to: 1, label: "Second invocation", detail: "🔥 WARM — reuses sandbox" },
      { from: 1, to: 4, label: "Reuse execution context", detail: "< 1ms overhead" },
      { from: 4, to: 0, label: "Fast response ✅", detail: "Warm: < 5ms overhead" },
      { from: 3, to: 3, label: "Idle → recycled (15min)", detail: "Context becomes COLD again" },
    ],
    durationInFrames: 360,
  },

  // ═══════════════════════════════════════════════════════════
  // AWS — MESSAGING (4 sequences)
  // ═══════════════════════════════════════════════════════════

  {
    id: "aws-sqs-long-polling",
    title: "SQS Short Polling vs Long Polling",
    subtitle: "Short polling: wasteful empty responses — Long polling: wait up to 20s, return batch, 90% cheaper",
    actors: ["Consumer", "SQS Queue", "Lambda (Worker)"],
    steps: [
      { from: 0, to: 1, label: "ReceiveMessage (short)", detail: "waitTime=0s, returns immediately" },
      { from: 1, to: 0, label: "Empty response ⚠️", detail: "Wasted API call + network cost" },
      { from: 0, to: 1, label: "ReceiveMessage (short)", detail: "Another empty poll!" },
      { from: 1, to: 0, label: "Empty again ❌", detail: "Short polling = frequent API calls" },
      { from: 0, to: 0, label: "Cost: 1M polls × $0.40", detail: "90% waste on empty responses" },
      { from: 0, to: 1, label: "ReceiveMessage (long)", detail: "waitTime=20s, holds connection open" },
      { from: 1, to: 1, label: "Message arrives! 🚀", detail: "Order #123 queued" },
      { from: 1, to: 0, label: "Batch of 10 messages", detail: "Consumer returns immediately" },
      { from: 0, to: 2, label: "Process batch", detail: "10 orders processed per invocation" },
      { from: 2, to: 0, label: "DeleteMessageBatch", detail: "Messages removed from queue" },
      { from: 0, to: 0, label: "Cost: 100K polls × $0.04", detail: "90% cheaper than short polling ✅" },
    ],
    durationInFrames: 360,
  },

  {
    id: "aws-sns-fanout",
    title: "SNS → SQS Fan-Out Pattern",
    subtitle: "Single SNS topic publishes to multiple SQS queues — each service gets every event with isolated retry",
    actors: ["Publisher (Order)", "SNS Topic", "Payment SQS", "Inventory SQS", "Notification SQS"],
    steps: [
      { from: 0, to: 1, label: "Publish OrderPlaced", detail: "event_type, order_id, amount" },
      { from: 1, to: 2, label: "Fan-out → Payment Queue", detail: "Subscribed with filter: payment_*" },
      { from: 1, to: 3, label: "Fan-out → Inventory Queue", detail: "Subscribed with filter: order_*" },
      { from: 1, to: 4, label: "Fan-out → Notification Queue", detail: "No filter: receives ALL events" },
      { from: 2, to: 2, label: "Payment Lambda processes", detail: "⚠️ FAILS! Retry 3× → DLQ" },
      { from: 3, to: 3, label: "Inventory deducted ✅", detail: "Independent processing" },
      { from: 4, to: 4, label: "Email sent to customer ✅", detail: "Independent processing" },
      { from: 2, to: 2, label: "Messages in DLQ", detail: "Manual redrive after fix" },
      { from: 0, to: 1, label: "Publish OrderCancelled", detail: "Different event type" },
      { from: 1, to: 4, label: "Only Notification gets it", detail: "Payment filter excludes cancelled" },
      { from: 2, to: 1, label: "Payment service ISOLATED ❌", detail: "Fails independently, others OK ✅" },
    ],
    durationInFrames: 330,
  },

  {
    id: "aws-kinesis-shard-scaling",
    title: "Kinesis Shard Allocation & Resharding",
    subtitle: "Partition key → hash → shard — hot key overloads one shard — split redistributes load",
    actors: ["Producer", "Kinesis Stream", "Shard 1 (key:a-f)", "Shard 2 (key:g-m)", "Shard 3 (key:n-z)"],
    steps: [
      { from: 0, to: 1, label: "PutRecord 'user_001'", detail: "hash(user_001) % 3 → shard 1" },
      { from: 0, to: 1, label: "PutRecord 'user_045'", detail: "hash(user_045) % 3 → shard 2" },
      { from: 0, to: 1, label: "PutRecord 'user_999'", detail: "hash(user_999) % 3 → shard 3" },
      { from: 1, to: 2, label: "Route to shard 1", detail: "1MB/s write, 1000 rec/s" },
      { from: 1, to: 3, label: "Route to shard 2", detail: "1MB/s write, 1000 rec/s" },
      { from: 1, to: 4, label: "Route to shard 3", detail: "1MB/s write, 1000 rec/s" },
      { from: 0, to: 1, label: "PutRecord 'viral_video' ×10K", detail: "⚠️ HOT KEY! All map to shard 2" },
      { from: 1, to: 3, label: "Shard 2 overloaded! ❌", detail: "1MB/s limit → throttled" },
      { from: 3, to: 3, label: "ProvisionedThroughputExceeded", detail: "Records rejected!" },
      { from: 0, to: 1, label: "Solution: split shard 2", detail: "Shard 2 → shard 2A + shard 2B" },
      { from: 1, to: 3, label: "hash. (viral) → 2A", detail: "Hot key gets own shard" },
      { from: 1, to: 2, label: "hash. (other) → 2B", detail: "Other keys spread" },
    ],
    durationInFrames: 360,
  },

  {
    id: "aws-eventbridge-routing",
    title: "EventBridge Event Bus & Routing",
    subtitle: "Event bus receives → content-based rules filter → route to Lambda, SQS, and Step Functions",
    actors: ["Event Source (DDB)", "EventBridge Bus", "Rule: High Value", "Rule: Audit", "Targets"],
    steps: [
      { from: 0, to: 1, label: "DynamoDB Stream event", detail: "NewOrder: amount=$1500" },
      { from: 1, to: 2, label: "Rule: order_amount >= 1000", detail: "Filter: high-value order" },
      { from: 2, to: 4, label: "Target: Step Functions", detail: "Orchestrate approval saga" },
      { from: 0, to: 1, label: "DynamoDB Stream event", detail: "NewOrder: amount=$50" },
      { from: 1, to: 3, label: "Rule: ALL orders", detail: "No filter, receives everything" },
      { from: 3, to: 4, label: "Target: SQS + Lambda", detail: "Log + index to Elasticsearch" },
      { from: 0, to: 1, label: "EC2 State Change event", detail: "instance = i-123, state = running" },
      { from: 1, to: 1, label: "Default event bus", detail: "AWS service events + custom" },
      { from: 1, to: 4, label: "Target: SNS topic", detail: "Notify on-call engineer" },
      { from: 0, to: 1, label: "Pipes: DDB Stream → SQS", detail: "Single source→target (cheaper)" },
      { from: 1, to: 1, label: "Rules: multi-target routing", detail: "Complex filtering & transforms" },
    ],
    durationInFrames: 330,
  },

  // ═══════════════════════════════════════════════════════════
  // AWS — SECURITY (4 sequences)
  // ═══════════════════════════════════════════════════════════

  {
    id: "aws-iam-permission-boundary",
    title: "IAM Permission Boundary Flow",
    subtitle: "User → Groups → Roles → Permission Boundary → SCP → Resource Policy — DENY always wins",
    actors: ["IAM User", "Permission Boundary", "SCP (Org)", "Effective Permissions"],
    steps: [
      { from: 0, to: 0, label: "Identity policies attached", detail: "ALLOW by default (EC2, S3, IAM)" },
      { from: 0, to: 1, label: "Permission boundary applied", detail: "Max: EC2:* + S3:* only" },
      { from: 1, to: 2, label: "SCP at OU level", detail: "Deny: IAM:* at org level" },
      { from: 2, to: 3, label: "→ Effective: EC2, S3 only", detail: "IAM boundary + SCP = trimmed" },
      { from: 0, to: 0, label: "Attempt: iam:CreateUser", detail: "❌ DENY by permission boundary" },
      { from: 0, to: 0, label: "Attempt: ec2:RunInstances", detail: "✅ ALLOWED by policy + boundary" },
      { from: 0, to: 1, label: "Developer creates a role", detail: "Role bounded to EC2 + S3" },
      { from: 1, to: 1, label: "AdminAccess attached", detail: "Boundary overrides → EC2+S3 only" },
      { from: 1, to: 3, label: "No privilege escalation ✅", detail: "Boundary prevents admin escape" },
    ],
    durationInFrames: 270,
  },

  {
    id: "aws-kms-envelope-encryption",
    title: "KMS Envelope Encryption",
    subtitle: "CMK (HSM) encrypts DEK → DEK encrypts data — encrypted DEK stored alongside ciphertext",
    actors: ["Application", "AWS KMS (CMK)", "Data Encryption Key", "Encrypted Data"],
    steps: [
      { from: 0, to: 1, label: "GenerateDataKey", detail: "Request a DEK under CMK" },
      { from: 1, to: 2, label: "Generate AES-256 DEK", detail: "CMK never leaves HSM ✅" },
      { from: 2, to: 0, label: "Plaintext DEK + Encrypted DEK", detail: "Use plaintext, discard after encryption" },
      { from: 0, to: 3, label: "Encrypt data with DEK", detail: "AES-256-GCM encryption" },
      { from: 3, to: 3, label: "Store: encrypted DEK || data", detail: "Encrypted DEK alongside ciphertext" },
      { from: 0, to: 1, label: "Decrypt: KMS:Decrypt", detail: "Pass encrypted DEK to KMS" },
      { from: 1, to: 2, label: "CMK decrypts DEK", detail: "Returns plaintext DEK" },
      { from: 2, to: 0, label: "Plaintext DEK returned", detail: "Key never leaves KMS in clear" },
      { from: 0, to: 3, label: "Decrypt data with DEK", detail: "AES-256-GCM decryption" },
      { from: 1, to: 2, label: "Key rotation (annual)", detail: "New backing key, old retained" },
    ],
    durationInFrames: 300,
  },

  {
    id: "aws-guardduty-multi-account",
    title: "GuardDuty Multi-Account Threat Detection",
    subtitle: "Security account as delegated admin — findings flow from 50 member accounts → centralized detection → auto-remediation",
    actors: ["Member Account 1", "Member Account 2", "Security Account (Admin)", "Auto-Remediation"],
    steps: [
      { from: 0, to: 0, label: "GuardDuty enabled locally", detail: "Monitoring EC2, IAM, S3 activity" },
      { from: 1, to: 1, label: "GuardDuty enabled locally", detail: "Monitoring EC2, IAM, S3 activity" },
      { from: 0, to: 2, label: "Findings → Security account", detail: "Cross-account aggregation via org" },
      { from: 1, to: 2, label: "Findings → Security account", detail: "All 50 accounts report centrally" },
      { from: 2, to: 2, label: "Security Hub aggregates", detail: "Cross-region findings dashboard" },
      { from: 0, to: 0, label: "⚠️ CryptoCurrency:EC2/", detail: "Crypto mining detected (ML + threat intel)" },
      { from: 0, to: 2, label: "HIGH severity finding", detail: "CryptoCurrency:EC2/BitcoinTool.B" },
      { from: 2, to: 3, label: "EventBridge → Lambda", detail: "Auto-remediation triggered" },
      { from: 3, to: 0, label: "Isolate instance (SG)", detail: "New SG: deny all egress" },
      { from: 3, to: 0, label: "Snapshot forensic", detail: "Capture for investigation" },
      { from: 2, to: 2, label: "Case resolved ✅", detail: "Automated incident response" },
    ],
    durationInFrames: 330,
  },

  {
    id: "aws-cognito-auth-flow",
    title: "Cognito Authentication & Authorization Flow",
    subtitle: "User → User Pool (JWT) → Identity Pool (AWS creds) → S3 / DynamoDB / API Gateway",
    actors: ["End User", "Cognito User Pool", "Cognito Identity Pool", "AWS Resources"],
    steps: [
      { from: 0, to: 1, label: "Sign in: username + password", detail: "Optional: MFA (TOTP/SMS)" },
      { from: 1, to: 1, label: "Validate credentials", detail: "Check password hash + MFA code" },
      { from: 1, to: 0, label: "JWT tokens returned", detail: "ID token + Access token + Refresh" },
      { from: 0, to: 2, label: "Exchange JWT for AWS creds", detail: "Cognito Identity Pool" },
      { from: 2, to: 2, label: "Map to IAM role", detail: "Authenticated role based on group" },
      { from: 2, to: 0, label: "Temporary STS credentials", detail: "AccessKey + SecretKey + SessionToken" },
      { from: 0, to: 3, label: "GET /users/123", detail: "API Gateway with IAM auth" },
      { from: 3, to: 0, label: "200 OK (user data)", detail: "Fine-grained access control" },
      { from: 0, to: 3, label: "PUT /object.txt", detail: "S3 with IAM policy per user" },
      { from: 0, to: 0, label: "Refresh token valid for 30 days", detail: "Silent re-auth without user" },
    ],
    durationInFrames: 300,
  },
];
