import { ClassDiagramData } from "./ClassDiagramAnimation";

// ─── Java LLD Systems ────────────────────────────────────

export const JAVA_ELEVATOR_CLASS_DIAGRAM: ClassDiagramData = {
  id: "java-elevator-class-diagram",
  title: "Java: Elevator System — Class Diagram",
  subtitle: "SOLID + State + Strategy + Observer Patterns — 40 floors, 6 elevators",
  classes: [
    {
      id: "ElevatorController",
      name: "ElevatorController",
      stereotype: "Facade + Observer",
      fields: [
        "- elevators: List<Elevator>",
        "- strategy: DispatchingStrategy",
        "- pendingRequests: Queue<Request>",
        "- emergencyMode: boolean",
      ],
      methods: [
        "+ requestElevator(floor, dir)",
        "+ activateFireAlarm()",
        "+ scheduleMaintenance(id)",
        "+ displayStatus()",
      ],
      x: 180,
      y: 180,
      width: 240,
      height: 130,
    },
    {
      id: "Elevator",
      name: "Elevator",
      stereotype: "State Machine",
      fields: [
        "- currentFloor: int",
        "- direction: Direction",
        "- doorState: DoorState",
        "- stops: NavigableSet<Int>",
        "- weightSensor: WeightSensor",
        "- vipMode: boolean",
      ],
      methods: [
        "+ addRequest(Request)",
        "+ openDoor() / closeDoor()",
        "+ activateFireMode()",
        "+ setVipMode(boolean)",
      ],
      x: 140,
      y: 400,
      width: 240,
      height: 140,
    },
    {
      id: "DispatchingStrategy",
      name: "DispatchingStrategy",
      stereotype: "interface <<Strategy>>",
      fields: [],
      methods: [
        "+ assignElevator(req, elevators)",
      ],
      x: 480,
      y: 400,
      width: 250,
      height: 70,
    },
    {
      id: "NearestCarStrategy",
      name: "NearestCarStrategy",
      fields: [],
      methods: [
        "+ assignElevator(): closest",
      ],
      x: 440,
      y: 550,
      width: 160,
      height: 60,
    },
    {
      id: "ScanStrategy",
      name: "ScanStrategy",
      fields: [],
      methods: [
        "+ assignElevator(): SCAN",
      ],
      x: 620,
      y: 550,
      width: 160,
      height: 60,
    },
    {
      id: "ElevatorObserver",
      name: "ElevatorObserver",
      stereotype: "interface <<Observer>>",
      fields: [],
      methods: [
        "+ onElevatorStopped(e, floor)",
        "+ onEmergency(e, type, msg)",
        "+ onOverload(e, load, cap)",
      ],
      x: 800,
      y: 180,
      width: 240,
      height: 95,
    },
    {
      id: "Request",
      name: "Request",
      stereotype: "record",
      fields: [
        "+ floor: int",
        "+ direction: Direction",
        "+ requestId: UUID",
      ],
      methods: [
        "+ isUrgent(): boolean",
      ],
      x: 490,
      y: 180,
      width: 200,
      height: 85,
    },
    {
      id: "WeightSensor",
      name: "WeightSensor",
      fields: [
        "- currentWeight: double",
        "- maxWeight: double",
      ],
      methods: [
        "+ addPassenger(kg): boolean",
        "+ isOverloaded(): boolean",
      ],
      x: 840,
      y: 400,
      width: 220,
      height: 85,
    },
  ],
  relationships: [
    { from: "ElevatorController", to: "Elevator", type: "composition", label: "manages ▸", fromMultiplicity: "1", toMultiplicity: "1..*" },
    { from: "ElevatorController", to: "DispatchingStrategy", type: "association", label: "uses ▸", fromMultiplicity: "1", toMultiplicity: "1" },
    { from: "ElevatorController", to: "ElevatorObserver", type: "association", label: "notifies ▸", fromMultiplicity: "1", toMultiplicity: "*" },
    { from: "DispatchingStrategy", to: "NearestCarStrategy", type: "inheritance", label: "◁ implements" },
    { from: "DispatchingStrategy", to: "ScanStrategy", type: "inheritance", label: "◁ implements" },
    { from: "Elevator", to: "Request", type: "association", label: "processes ▸" },
    { from: "Elevator", to: "WeightSensor", type: "composition", label: "has ▸", fromMultiplicity: "1", toMultiplicity: "1" },
    { from: "Elevator", to: "ElevatorObserver", type: "association", label: "notifies ▸" },
    { from: "ElevatorController", to: "Request", type: "association", label: "creates ▸" },
  ],
  durationInFrames: 360,
};

export const JAVA_MEETING_CLASS_DIAGRAM: ClassDiagramData = {
  id: "java-meeting-class-diagram",
  title: "Java: Meeting Scheduler — Class Diagram",
  subtitle: "SOLID + Strategy + Observer + Facade Patterns — Enterprise calendar",
  classes: [
    {
      id: "MeetingScheduler",
      name: "MeetingScheduler",
      stereotype: "Facade",
      fields: [
        "- conflictDetector: ConflictDetector",
        "- bookingPolicy: RoomBookingPolicy",
        "- roomRecommender: RoomRecommender",
        "- observers: List<MeetingObserver>",
      ],
      methods: [
        "+ scheduleMeeting(...): Meeting",
        "+ cancelMeeting(id, reason)",
        "+ findAvailableSlots(room, date, dur)",
        "+ getDailyAgenda(email, date)",
      ],
      x: 100,
      y: 180,
      width: 260,
      height: 140,
    },
    {
      id: "Meeting",
      name: "Meeting",
      fields: [
        "- title, description: String",
        "- slot: TimeSlot",
        "- organizer: Participant",
        "- attendees: List<Participant>",
        "- status: MeetingStatus",
      ],
      methods: [
        "+ reschedule(newSlot)",
        "+ cancel(reason)",
        "+ respond(email, status)",
        "+ toDetailedString(): String",
      ],
      x: 100,
      y: 430,
      width: 240,
      height: 130,
    },
    {
      id: "MeetingSeries",
      name: "MeetingSeries",
      fields: [
        "- seriesId, title: String",
        "- pattern: RecurrencePattern",
        "- exceptionDates: Set<LocalDate>",
        "- maxInstances: int",
      ],
      methods: [
        "+ expand(from, to): List<Instance>",
        "+ cancelInstance(date)",
        "+ modifyInstance(date, slot)",
      ],
      x: 430,
      y: 430,
      width: 230,
      height: 120,
    },
    {
      id: "ConflictDetector",
      name: "ConflictDetector",
      fields: [
        "- roomCalendar: Map<Room, Set<Slot>>",
        "- participantCalendar: Map<Email, Set<Slot>>",
      ],
      methods: [
        "+ findConflict(roomId, slot): Optional",
        "+ findParticipantConflicts(...)",
        "+ findAvailableSlots(...)",
        "+ findMutualSlots(...)",
      ],
      x: 750,
      y: 430,
      width: 250,
      height: 120,
    },
    {
      id: "RoomBookingPolicy",
      name: "RoomBookingPolicy",
      stereotype: "interface <<Strategy>>",
      fields: [],
      methods: [
        "+ canBook(room, slot, count, feats): bool",
        "+ rejectionReason(): String",
      ],
      x: 460,
      y: 180,
      width: 230,
      height: 75,
    },
    {
      id: "RoomRecommender",
      name: "RoomRecommender",
      fields: [
        "- rooms: List<Room>",
      ],
      methods: [
        "+ recommendRooms(count, feats): List",
        "+ findBestRoom(...): Optional",
      ],
      x: 760,
      y: 180,
      width: 240,
      height: 85,
    },
    {
      id: "MeetingObserver",
      name: "MeetingObserver",
      stereotype: "interface <<Observer>>",
      fields: [],
      methods: [
        "+ onMeetingCreated(m)",
        "+ onMeetingCancelled(m, reason)",
        "+ onMeetingReminder(m)",
      ],
      x: 1120,
      y: 180,
      width: 240,
      height: 90,
    },
    {
      id: "MeetingAnalytics",
      name: "MeetingAnalytics",
      fields: [
        "- meetingsByRoom: Map<String, Int>",
        "- totalMeetings: AtomicLong",
      ],
      methods: [
        "+ recordMeeting(meeting)",
        "+ printReport()",
      ],
      x: 1120,
      y: 430,
      width: 220,
      height: 80,
    },
  ],
  relationships: [
    { from: "MeetingScheduler", to: "Meeting", type: "composition", label: "creates ▸" },
    { from: "MeetingScheduler", to: "ConflictDetector", type: "composition", label: "has ▸" },
    { from: "MeetingScheduler", to: "RoomBookingPolicy", type: "association", label: "uses ▸" },
    { from: "MeetingScheduler", to: "RoomRecommender", type: "composition", label: "has ▸" },
    { from: "MeetingScheduler", to: "MeetingObserver", type: "association", label: "notifies ▸" },
    { from: "MeetingScheduler", to: "MeetingAnalytics", type: "composition", label: "tracks ▸" },
    { from: "Meeting", to: "MeetingSeries", type: "aggregation", label: "part of ▸" },
    { from: "MeetingScheduler", to: "MeetingSeries", type: "association", label: "manages ▸" },
  ],
  durationInFrames: 360,
};

export const JAVA_HOTEL_CLASS_DIAGRAM: ClassDiagramData = {
  id: "java-hotel-class-diagram",
  title: "Java: Hotel Booking System — Class Diagram",
  subtitle: "SOLID + Strategy + Decorator + Observer Patterns — 50 rooms, 6 types",
  classes: [
    {
      id: "HotelBookingService",
      name: "HotelBookingService",
      stereotype: "Facade",
      fields: [
        "- inventory: InventoryManager",
        "- pricing: PricingStrategy",
        "- waitlist: WaitlistManager",
        "- loyalty: LoyaltyPointsTracker",
        "- revenue: RevenueManager",
      ],
      methods: [
        "+ createBooking(guest, room, stay)",
        "+ cancelBooking(id): double",
        "+ createGroupBooking(...)",
        "+ printAvailability(type, from, days)",
      ],
      x: 80,
      y: 180,
      width: 260,
      height: 145,
    },
    {
      id: "Booking",
      name: "Booking",
      fields: [
        "- guest: Guest",
        "- room: Room",
        "- stay: DateRange",
        "- totalAmount: double",
        "- status: BookingStatus",
      ],
      methods: [
        "+ cancel(): double",
        "+ checkIn() / checkOut()",
      ],
      x: 80,
      y: 440,
      width: 220,
      height: 110,
    },
    {
      id: "InventoryManager",
      name: "InventoryManager",
      fields: [
        "- availability: Map<RoomType, Map<Date, Int>>",
      ],
      methods: [
        "+ checkAvailability(type, range): bool",
        "+ reserveBlock(type, range, count): bool",
        "+ suggestUpgrade(type, range): RoomType",
      ],
      x: 370,
      y: 440,
      width: 240,
      height: 110,
    },
    {
      id: "PricingStrategy",
      name: "PricingStrategy",
      stereotype: "interface <<Strategy + Decorator>>",
      fields: [],
      methods: [
        "+ calculatePrice(type, stay, guest): double",
        "+ description(): String",
      ],
      x: 370,
      y: 180,
      width: 260,
      height: 75,
    },
    {
      id: "BaseRatePricing",
      name: "BaseRatePricing",
      fields: [],
      methods: [
        "+ calculatePrice(): base rate",
      ],
      x: 340,
      y: 300,
      width: 150,
      height: 55,
    },
    {
      id: "LoyaltyPricing",
      name: "LoyaltyPricing",
      fields: [
        "- wrapped: PricingStrategy",
      ],
      methods: [
        "+ calculatePrice(): apply discount",
      ],
      x: 510,
      y: 300,
      width: 150,
      height: 55,
    },
    {
      id: "WaitlistManager",
      name: "WaitlistManager",
      fields: [
        "- waitlists: Map<RoomType, PQ<Entry>>",
      ],
      methods: [
        "+ addToWaitlist(entry)",
        "+ getNextAvailable(type): Optional",
      ],
      x: 720,
      y: 440,
      width: 230,
      height: 90,
    },
    {
      id: "LoyaltyPointsTracker",
      name: "LoyaltyPointsTracker",
      fields: [
        "- guests: Map<String, Guest>",
      ],
      methods: [
        "+ earnPoints(guest, amount): int",
        "+ redeemPoints(guest, pts, amt): bool",
      ],
      x: 720,
      y: 180,
      width: 250,
      height: 85,
    },
    {
      id: "RevenueManager",
      name: "RevenueManager",
      fields: [
        "- dailyRevenue: Map<RoomType, Map<Date, $>>",
      ],
      methods: [
        "+ recordRevenue(type, date, amount)",
        "+ printRevenueReport()",
      ],
      x: 1060,
      y: 440,
      width: 230,
      height: 80,
    },
  ],
  relationships: [
    { from: "HotelBookingService", to: "Booking", type: "composition", label: "creates ▸" },
    { from: "HotelBookingService", to: "InventoryManager", type: "composition", label: "manages ▸" },
    { from: "HotelBookingService", to: "PricingStrategy", type: "association", label: "uses ▸" },
    { from: "HotelBookingService", to: "WaitlistManager", type: "composition", label: "has ▸" },
    { from: "HotelBookingService", to: "LoyaltyPointsTracker", type: "composition", label: "tracks ▸" },
    { from: "HotelBookingService", to: "RevenueManager", type: "composition", label: "reports ▸" },
    { from: "PricingStrategy", to: "BaseRatePricing", type: "inheritance", label: "◁ base" },
    { from: "PricingStrategy", to: "LoyaltyPricing", type: "inheritance", label: "◁ decorator" },
    { from: "InventoryManager", to: "Booking", type: "association", label: "reserves ▸" },
  ],
  durationInFrames: 390,
};

// ─── Go LLD Systems ──────────────────────────────────────

export const GO_KVSTORE_CLASS_DIAGRAM: ClassDiagramData = {
  id: "go-kvstore-class-diagram",
  title: "Go: In-Memory KV Store — Struct Diagram",
  subtitle: "CSP + Strategy Pattern + Generics — TTL, Eviction, Watch, CAS, Namespaces",
  classes: [
    {
      id: "KVStore",
      name: "KVStore",
      fields: [
        "- data: map[string]*Value",
        "- namespaces: map[string]map[string]*Value",
        "- eviction: EvictionPolicy",
        "- maxSize: int64",
        "- ttlHeap: expiryHeap",
        "- subscriptions: []*WatchSubscription",
      ],
      methods: [
        "+ Set(key, val, ttl) error",
        "+ Get(key) (interface{}, bool)",
        "+ CAS(key, ver, val, ttl) CASResult",
        "+ Subscribe(pattern, ns, buf) *Sub",
        "+ Snapshot(path) error",
      ],
      x: 80,
      y: 180,
      width: 280,
      height: 165,
    },
    {
      id: "Value",
      name: "Value",
      fields: [
        "- Data: interface{}",
        "- ExpiresAt: *time.Time",
        "- AccessCount: int64",
        "- Version: uint64",
        "- Metadata: map[string]string",
      ],
      methods: [
        "+ IsExpired(): bool",
        "+ ExtendTTL(ttl): bool",
        "+ ClearTTL()",
      ],
      x: 80,
      y: 440,
      width: 240,
      height: 115,
    },
    {
      id: "EvictionPolicy",
      name: "EvictionPolicy",
      stereotype: "interface <<Strategy>>",
      fields: [],
      methods: [
        "+ Record(key)",
        "+ Evict() string",
        "+ Remove(key)",
        "+ Name() string",
      ],
      x: 440,
      y: 180,
      width: 230,
      height: 80,
    },
    {
      id: "LRUPolicy",
      name: "LRUPolicy",
      fields: [
        "- accessOrder: *list.List",
        "- entries: map[string]*Element",
      ],
      methods: [
        "+ Record(key): move to front",
        "+ Evict(): remove back",
      ],
      x: 380,
      y: 320,
      width: 150,
      height: 80,
    },
    {
      id: "LFUPolicy",
      name: "LFUPolicy",
      fields: [
        "- freqs: map[string]int64",
        "- minHeap: *freqHeap",
      ],
      methods: [
        "+ Record(key): increment freq",
        "+ Evict(): pop min freq",
      ],
      x: 560,
      y: 320,
      width: 160,
      height: 80,
    },
    {
      id: "WatchSubscription",
      name: "WatchSubscription",
      fields: [
        "- pattern: string",
        "- namespace: string",
        "- channel: chan WatchEvent",
        "- active: atomic.Bool",
      ],
      methods: [],
      x: 440,
      y: 450,
      width: 240,
      height: 70,
    },
    {
      id: "KVStoreWithCleanup",
      name: "KVStoreWithCleanup",
      fields: [
        "- *KVStore (embedded)",
        "- stopCh: chan struct{}",
      ],
      methods: [
        "+ Shutdown()",
      ],
      x: 800,
      y: 180,
      width: 250,
      height: 75,
    },
    {
      id: "WriteAheadLog",
      name: "WriteAheadLog",
      fields: [
        "- filePath: string",
        "- entries: []WALEntry",
        "- enabled: bool",
      ],
      methods: [
        "+ Append(entry) error",
      ],
      x: 800,
      y: 330,
      width: 230,
      height: 70,
    },
  ],
  relationships: [
    { from: "KVStore", to: "Value", type: "composition", label: "stores ▸", fromMultiplicity: "1", toMultiplicity: "*" },
    { from: "KVStore", to: "EvictionPolicy", type: "association", label: "uses ▸" },
    { from: "EvictionPolicy", to: "LRUPolicy", type: "inheritance", label: "◁ implements" },
    { from: "EvictionPolicy", to: "LFUPolicy", type: "inheritance", label: "◁ implements" },
    { from: "KVStore", to: "WatchSubscription", type: "association", label: "manages ▸", fromMultiplicity: "1", toMultiplicity: "*" },
    { from: "KVStoreWithCleanup", to: "KVStore", type: "inheritance", label: "◁ embeds" },
    { from: "KVStore", to: "WriteAheadLog", type: "composition", label: "logs ▸", fromMultiplicity: "1", toMultiplicity: "1" },
  ],
  durationInFrames: 360,
};

export const GO_TASKQUEUE_CLASS_DIAGRAM: ClassDiagramData = {
  id: "go-taskqueue-class-diagram",
  title: "Go: Task Queue / Worker Pool — Struct Diagram",
  subtitle: "CSP + Worker Pool + Pipeline — Priority Queue, Scheduling, Dead Letter",
  classes: [
    {
      id: "TaskQueue",
      name: "TaskQueue",
      fields: [
        "- pending: PriorityQueue",
        "- running: map[string]*Task",
        "- handlers: map[string]TaskHandler",
        "- deadLetter: *DeadLetterQueue",
        "- batchProcessor: *BatchProcessor",
        "- scheduled: *ScheduledTaskQueue",
      ],
      methods: [
        "+ Enqueue(task)",
        "+ Dequeue() *Task",
        "+ Schedule(task, time)",
        "+ EnqueueWithDep(task, deps)",
        "+ Stats() map[string]interface{}",
      ],
      x: 60,
      y: 180,
      width: 280,
      height: 165,
    },
    {
      id: "Task",
      name: "Task",
      fields: [
        "- ID, Type: string",
        "- Payload: map[string]interface{}",
        "- Priority: TaskPriority",
        "- Status: TaskStatus",
        "- RetryCount, MaxRetries: int",
        "- Dependencies: []string",
      ],
      methods: [],
      x: 60,
      y: 450,
      width: 240,
      height: 110,
    },
    {
      id: "WorkerPool",
      name: "WorkerPool",
      fields: [
        "- queue: *TaskQueue",
        "- numWorkers: int",
        "- handlers: map[string]TaskHandler",
        "- ctx: context.Context",
      ],
      methods: [
        "+ RegisterHandler(handler)",
        "+ Start() <-chan TaskResult",
        "+ Shutdown()",
      ],
      x: 420,
      y: 180,
      width: 240,
      height: 115,
    },
    {
      id: "TaskHandler",
      name: "TaskHandler",
      stereotype: "interface <<Strategy>>",
      fields: [],
      methods: [
        "+ Handle(ctx, task) (interface{}, error)",
        "+ Type() string",
      ],
      x: 420,
      y: 380,
      width: 220,
      height: 70,
    },
    {
      id: "DeadLetterQueue",
      name: "DeadLetterQueue",
      fields: [
        "- tasks: []*Task",
        "- maxSize: int",
      ],
      methods: [
        "+ Add(task)",
        "+ Requeue(queue, id): bool",
      ],
      x: 750,
      y: 450,
      width: 210,
      height: 75,
    },
    {
      id: "ScheduledTaskQueue",
      name: "ScheduledTaskQueue",
      fields: [
        "- tasks: []*Task (sorted)",
        "- notifyCh: chan struct{}",
      ],
      methods: [
        "+ Add(task)",
        "+ GetReady() []*Task",
        "+ NextScheduled() Duration",
      ],
      x: 750,
      y: 180,
      width: 240,
      height: 100,
    },
    {
      id: "BatchProcessor",
      name: "BatchProcessor",
      fields: [
        "- batches: map[string][]*Task",
        "- config: BatchConfig",
      ],
      methods: [
        "+ Add(groupID, task)",
        "+ Flush(ctx, group) []Result",
      ],
      x: 750,
      y: 340,
      width: 230,
      height: 80,
    },
    {
      id: "GenericHandler",
      name: "GenericHandler",
      fields: [
        "- taskType: string",
        "- processFn: func",
      ],
      methods: [
        "+ Handle(ctx, task): delegate",
      ],
      x: 420,
      y: 500,
      width: 220,
      height: 60,
    },
  ],
  relationships: [
    { from: "TaskQueue", to: "Task", type: "composition", label: "queues ▸" },
    { from: "TaskQueue", to: "WorkerPool", type: "association", label: "feeds ▸" },
    { from: "TaskQueue", to: "DeadLetterQueue", type: "composition", label: "dead letters ▸" },
    { from: "TaskQueue", to: "ScheduledTaskQueue", type: "composition", label: "schedules ▸" },
    { from: "TaskQueue", to: "BatchProcessor", type: "association", label: "batches ▸" },
    { from: "WorkerPool", to: "TaskHandler", type: "association", label: "uses ▸" },
    { from: "TaskHandler", to: "GenericHandler", type: "inheritance", label: "◁ implements" },
  ],
  durationInFrames: 360,
};

export const GO_WEBCRAWLER_CLASS_DIAGRAM: ClassDiagramData = {
  id: "go-webcrawler-class-diagram",
  title: "Go: Web Crawler — Struct Diagram",
  subtitle: "CSP + Fan-Out/Fan-In + Rate Limiting — Workers, Sitemaps, Robots.txt",
  classes: [
    {
      id: "WebCrawler",
      name: "WebCrawler",
      fields: [
        "- workers: int",
        "- maxDepth, maxPages: int",
        "- frontier: *URLFrontier",
        "- fetcher: *Fetcher",
        "- filters: []URLFilter",
        "- stats: *CrawlStats",
      ],
      methods: [
        "+ Crawl(ctx, seeds) (<-chan Page, err)",
        "+ AddFilter(filter)",
      ],
      x: 60,
      y: 180,
      width: 260,
      height: 140,
    },
    {
      id: "URLFrontier",
      name: "URLFrontier",
      fields: [
        "- entries: []*FrontierEntry",
        "- visited: *VisitTracker",
      ],
      methods: [
        "+ Push(req)",
        "+ Pop() *CrawlRequest",
        "+ IsVisited(url): bool",
      ],
      x: 60,
      y: 420,
      width: 230,
      height: 100,
    },
    {
      id: "Fetcher",
      name: "Fetcher",
      fields: [
        "- rateLimiter: *PerDomainRateLimiter",
        "- robots: *RobotsChecker",
        "- crawlDelay: Duration",
      ],
      methods: [
        "+ Fetch(ctx, req) Page",
      ],
      x: 400,
      y: 180,
      width: 230,
      height: 90,
    },
    {
      id: "Page",
      name: "Page",
      fields: [
        "- URL, Title: string",
        "- Status, Depth, Size: int",
        "- Links: []string",
        "- ContentType: string",
        "- Latency: Duration",
      ],
      methods: [],
      x: 400,
      y: 420,
      width: 220,
      height: 110,
    },
    {
      id: "RobotsChecker",
      name: "RobotsChecker",
      fields: [
        "- rules: map[string]*RobotsRule",
      ],
      methods: [
        "+ IsAllowed(url): bool",
        "+ GetCrawlDelay(domain): Duration",
      ],
      x: 730,
      y: 420,
      width: 240,
      height: 85,
    },
    {
      id: "SitemapParser",
      name: "SitemapParser",
      fields: [
        "- sitemaps: map[string][]string",
      ],
      methods: [
        "+ FetchAndParse(ctx, domain): []string",
      ],
      x: 730,
      y: 180,
      width: 230,
      height: 75,
    },
    {
      id: "URLFilter",
      name: "URLFilter",
      stereotype: "interface",
      fields: [],
      methods: [
        "+ Allow(url): bool",
        "+ Name(): string",
      ],
      x: 400,
      y: 280,
      width: 200,
      height: 65,
    },
    {
      id: "PerDomainRateLimiter",
      name: "PerDomainRateLimiter",
      fields: [
        "- limiters: map[string]*RateLimiter",
        "- defaultRPS: float64",
      ],
      methods: [
        "+ Allow(domain): bool",
      ],
      x: 730,
      y: 310,
      width: 260,
      height: 70,
    },
    {
      id: "CrawlStats",
      name: "CrawlStats",
      fields: [
        "- PagesCrawled: atomic.Int64",
        "- ErrorsByType: map[string]int64",
      ],
      methods: [
        "+ RecordError(type)",
        "+ Print()",
      ],
      x: 1060,
      y: 420,
      width: 220,
      height: 80,
    },
  ],
  relationships: [
    { from: "WebCrawler", to: "URLFrontier", type: "composition", label: "has ▸" },
    { from: "WebCrawler", to: "Fetcher", type: "composition", label: "fetches ▸" },
    { from: "WebCrawler", to: "URLFilter", type: "association", label: "filters ▸" },
    { from: "WebCrawler", to: "CrawlStats", type: "composition", label: "tracks ▸" },
    { from: "WebCrawler", to: "SitemapParser", type: "composition", label: "parses ▸" },
    { from: "Fetcher", to: "PerDomainRateLimiter", type: "composition", label: "rate limits ▸" },
    { from: "Fetcher", to: "RobotsChecker", type: "composition", label: "checks ▸" },
    { from: "Fetcher", to: "Page", type: "dependency", label: "returns ▸" },
    { from: "URLFrontier", to: "Page", type: "association", label: "discovers ▸" },
  ],
  durationInFrames: 390,
};

// ─── Combined Export ─────────────────────────────────────

export const ALL_CLASS_DIAGRAMS: ClassDiagramData[] = [
  JAVA_ELEVATOR_CLASS_DIAGRAM,
  JAVA_MEETING_CLASS_DIAGRAM,
  JAVA_HOTEL_CLASS_DIAGRAM,
  GO_KVSTORE_CLASS_DIAGRAM,
  GO_TASKQUEUE_CLASS_DIAGRAM,
  GO_WEBCRAWLER_CLASS_DIAGRAM,
];
