import { SequenceData } from "./SequenceDiagram";

export const SECURITY_SEQUENCES: SequenceData[] = [
  {
    id: "sec-oauth2-pkce",
    title: "OAuth2 Authorization Code + PKCE",
    subtitle: "Mobile App → Backend → Google Auth Server — Secure Login Flow",
    actors: ["Mobile App", "Backend API", "Google OAuth", "User"],
    steps: [
      { from: 0, to: 1, label: "Login Request", detail: "Wants to authenticate with Google" },
      { from: 1, to: 1, label: "Generate PKCE params", detail: "code_verifier = random(128 bytes)" },
      { from: 1, to: 1, label: "Compute code_challenge", detail: "SHA256(code_verifier) → base64" },
      { from: 1, to: 0, label: "Open browser to Auth URL", detail: "https://accounts.google.com/o/oauth2/auth + code_challenge" },
      { from: 0, to: 3, label: "User authenticates", detail: "Logs in with Google credentials" },
      { from: 3, to: 2, label: "Consent granted", detail: "App requests: profile, email" },
      { from: 2, to: 0, label: "Authorization code returned", detail: "Redirect URI with auth code" },
      { from: 0, to: 1, label: "Exchange code + verifier", detail: "POST /auth/google/callback" },
      { from: 1, to: 2, label: "Token request", detail: "auth_code + code_verifier + client_id" },
      { from: 2, to: 2, label: "Verify PKCE", detail: "SHA256(verifier) == code_challenge?" },
      { from: 2, to: 1, label: "Tokens issued", detail: "access_token + refresh_token + id_token" },
      { from: 1, to: 1, label: "Verify id_token", detail: "Validate signature, iss, aud, nonce" },
      { from: 1, to: 0, label: "✅ Authenticated!", detail: "Access token + refresh token issued" },
    ],
    durationInFrames: 360,
  },
  {
    id: "sec-jwt-revocation",
    title: "JWT Token Revocation & Key Rotation",
    subtitle: "Client → API Gateway → Auth Service → Microservice — Version-Based Revocation",
    actors: ["Client", "API Gateway", "Auth Service", "Microservice"],
    steps: [
      { from: 0, to: 1, label: "Request with JWT", detail: "Authorization: Bearer <token>" },
      { from: 1, to: 2, label: "Validate JWT", detail: "Check signature + expiry" },
      { from: 2, to: 2, label: "Verify token version", detail: "User's current ver == token ver?" },
      { from: 2, to: 1, label: "JWT valid", detail: "User: Alice, Role: admin, Ver: 3" },
      { from: 1, to: 3, label: "Forward request", detail: "x-user-id: 42, x-user-role: admin" },
      { from: 3, to: 1, label: "Response", detail: "200 OK — requested data" },
      { from: 1, to: 0, label: "✅ Request fulfilled", detail: "Stateless verification — no DB lookup" },
      { from: 0, to: 2, label: "Logout everywhere!", detail: "User revokes ALL sessions" },
      { from: 2, to: 2, label: "Increment token version", detail: "ver: 3 → 4 (invalidates all old JWTs)" },
      { from: 2, to: 2, label: "Delete refresh tokens", detail: "DELETE FROM refresh_tokens WHERE user_id=42" },
      { from: 2, to: 0, label: "All sessions revoked", detail: "Max 15 min until version propagation" },
      { from: 0, to: 1, label: "Old JWT (ver=3)", detail: "Trying to use revoked token" },
      { from: 1, to: 2, label: "Validate JWT", detail: "Signature OK — checking version..." },
      { from: 2, to: 1, label: "REVOKED!", detail: "Token ver(3) != current ver(4)" },
      { from: 1, to: 0, label: "❌ 401 Unauthorized", detail: "Must re-authenticate" },
    ],
    durationInFrames: 390,
  },
  {
    id: "sec-ssrf-defense",
    title: "SSRF Attack & Defense",
    subtitle: "Attacker → App Server → Metadata Endpoint — Multi-Layer Prevention",
    actors: ["Attacker", "App Server", "AWS Metadata", "SSRF Protector"],
    steps: [
      { from: 0, to: 1, label: "POST /fetch-url", detail: "url=http://169.254.169.254/latest/meta-data/" },
      { from: 1, to: 3, label: "Validate URL", detail: "Check allowlist + parse hostname" },
      { from: 3, to: 3, label: "Resolve hostname → IP", detail: "169.254.169.254 detected!" },
      { from: 3, to: 1, label: "⛔ BLOCKED", detail: "IP in blocked private ranges" },
      { from: 1, to: 0, label: "❌ 400 Bad Request", detail: "URL points to blocked resource" },
      { from: 0, to: 1, label: "Try DNS rebinding", detail: "example.com resolves to 8.8.8.8 first" },
      { from: 1, to: 3, label: "Validate + resolve", detail: "8.8.8.8 — public IP, allowed" },
      { from: 3, to: 1, label: "Proceed with request", detail: "Single connection, no DNS re-lookup" },
      { from: 1, to: 2, label: "fetch(8.8.8.8)", detail: "DNS rebinded → 10.0.0.1? NO!" },
      { from: 1, to: 0, label: "✅ Safe result", detail: "DNS rebinding prevented (IP pinned)" },
      { from: 0, to: 1, label: "Try IMDSv2 endpoint", detail: "Requires session token PUT" },
      { from: 1, to: 3, label: "Validate URL", detail: "Same IP block, blocked again" },
      { from: 3, to: 1, label: "⛔ BLOCKED", detail: "IMDSv2 requires token + TTL=1" },
      { from: 1, to: 0, label: "❌ SSRF prevented", detail: "Multi-layer defense wins" },
    ],
    durationInFrames: 390,
  },
  {
    id: "sec-vault-dynamic",
    title: "Vault Dynamic Secrets",
    subtitle: "App Service → Vault → Database — Auto-Expiring Credentials",
    actors: ["App Service", "HashiCorp Vault", "PostgreSQL DB", "Security Admin"],
    steps: [
      { from: 3, to: 1, label: "Configure DB plugin", detail: "vault write database/config/prod-db" },
      { from: 3, to: 1, label: "Create role", detail: "app-role: creation_statements + TTL" },
      { from: 0, to: 1, label: "Request credentials", detail: "GET /v1/database/creds/app-role" },
      { from: 1, to: 1, label: "Generate dynamic creds", detail: "CREATE USER 'v-app-4f3a' WITH PASSWORD '...'" },
      { from: 1, to: 2, label: "Create DB user", detail: "GRANT SELECT, INSERT, UPDATE ON ALL TABLES" },
      { from: 2, to: 1, label: "User created", detail: "Valid until: now + 1 hour" },
      { from: 1, to: 0, label: "Credentials issued", detail: "username: v-app-4f3a, ttl: 3600s" },
      { from: 0, to: 2, label: "Connect to DB", detail: "Using dynamic credentials" },
      { from: 2, to: 0, label: "✅ Connected!", detail: "Valid for 1 hour of queries" },
      { from: 0, to: 1, label: "Renew lease (30 min)", detail: "Extend TTL before expiry" },
      { from: 1, to: 0, label: "Lease renewed", detail: "New TTL: now + 3600s" },
      { from: 0, to: 0, label: "Processing queries", detail: "Credential auto-expires if not renewed" },
      { from: 1, to: 1, label: "Lease expires", detail: "v-app-4f3a → INVALID" },
      { from: 1, to: 2, label: "Drop DB user", detail: "Cleaned up automatically" },
    ],
    durationInFrames: 360,
  },
  {
    id: "sec-csrf-defense",
    title: "CSRF Attack & Double-Submit Cookie Defense",
    subtitle: "Browser → Victim Server — Cross-Site Request Forgery Prevention",
    actors: ["Browser", "Victim Server", "Attacker Site", "CSRF Token Service"],
    steps: [
      { from: 0, to: 1, label: "Login to bank.com", detail: "Session cookie set: SameSite=Strict" },
      { from: 1, to: 0, label: "Session established", detail: "csrf_token cookie also set (not HttpOnly)" },
      { from: 0, to: 2, label: "Visits attacker.com", detail: "Attacker's malicious page loads" },
      { from: 2, to: 0, label: "Auto-submit form", detail: "<form action='https://bank.com/transfer'>" },
      { from: 0, to: 1, label: "POST /transfer $1000", detail: "X-CSRF-Token header missing!" },
      { from: 1, to: 3, label: "Verify CSRF token", detail: "Check cookie vs header values" },
      { from: 3, to: 1, label: "⛔ No header token!", detail: "CSRF validation FAILED" },
      { from: 1, to: 0, label: "❌ 403 Forbidden", detail: "Cross-site request blocked" },
      { from: 0, to: 1, label: "Legit POST /transfer", detail: "X-CSRF-Token: <from cookie>" },
      { from: 1, to: 3, label: "Verify CSRF token", detail: "Compare cookie_token vs header_token" },
      { from: 3, to: 1, label: "✅ Tokens match!", detail: "SHA256(cookie) == SHA256(header)" },
      { from: 1, to: 0, label: "✅ Transfer processed", detail: "$100 sent — legitimate request" },
    ],
    durationInFrames: 330,
  },
  {
    id: "sec-sqli-defense",
    title: "SQL Injection Attack & Defense",
    subtitle: "Attacker → App → Database — Parameterized Query & Defense-in-Depth",
    actors: ["Attacker", "Web App", "Database", "WAF"],
    steps: [
      { from: 0, to: 1, label: "Search: ' OR 1=1; --", detail: "Classic tautology injection" },
      { from: 1, to: 1, label: "Build query", detail: "f\"SELECT * FROM users WHERE name = '{input}'\"" },
      { from: 1, to: 2, label: "Query with injection", detail: "SELECT * FROM users WHERE name = '' OR 1=1; --" },
      { from: 2, to: 1, label: "⚠️ All users leaked!", detail: "Entire users table returned" },
      { from: 0, to: 1, label: "Blind SQLi: timing", detail: "' OR (SELECT pg_sleep(5)) --" },
      { from: 1, to: 1, label: "Switch to parameterized", detail: "cursor.execute(..., (input,))" },
      { from: 0, to: 1, label: "Try same injection", detail: "' OR 1=1; DROP TABLE users; --" },
      { from: 1, to: 1, label: "Parameterize query", detail: "Input treated as DATA, not SQL code" },
      { from: 1, to: 2, label: "Safe query", detail: "WHERE name = \"' OR 1=1; DROP TABLE...\"" },
      { from: 2, to: 1, label: "No results (literal match)", detail: "Injection failed — safe!" },
      { from: 0, to: 1, label: "Try NoSQL injection", detail: '{"password": {"$ne": ""}}' },
      { from: 1, to: 3, label: "WAF blocks NoSQL", detail: "AWS WAF SQLI rule group" },
      { from: 3, to: 1, label: "Request blocked", detail: "WAF: Malicious input detected" },
      { from: 1, to: 0, label: "❌ 403 Blocked", detail: "Parameterized + WAF = Defense in Depth" },
    ],
    durationInFrames: 390,
  },
  {
    id: "sec-encryption-lifecycle",
    title: "Multi-Layer Encryption Lifecycle",
    subtitle: "Client → App → Database → Storage — TLS, Field Encryption, TDE & Envelope Keys",
    actors: ["Client", "App Server", "Database", "AWS KMS"],
    steps: [
      { from: 0, to: 1, label: "HTTPS request (TLS 1.3)", detail: "Encrypted in transit — AES-256-GCM" },
      { from: 1, to: 1, label: "Server decrypts TLS", detail: "TLS 1.3 handshake complete" },
      { from: 1, to: 3, label: "Request DEK from KMS", detail: "GenerateDataKey for field-level encrypt" },
      { from: 3, to: 1, label: "DEK (plaintext + ciphertext)", detail: "AES-256 DEK — KEK never leaves KMS" },
      { from: 1, to: 1, label: "Encrypt PHI fields", detail: "Fernet(DEK).encrypt(ssn) → ciphertext" },
      { from: 1, to: 2, label: "Write encrypted data", detail: "SSN encrypted, DEK blob stored alongside" },
      { from: 2, to: 2, label: "TDE encrypts pages", detail: "Database-level: AES-256 page encryption" },
      { from: 2, to: 1, label: "Data written securely", detail: "Three layers of encryption applied" },
      { from: 0, to: 1, label: "Read PHI record", detail: "Request to decrypt stored data" },
      { from: 1, to: 3, label: "Decrypt DEK via KMS", detail: "Decrypt(encrypted_dek) → plaintext DEK" },
      { from: 3, to: 1, label: "DEK plaintext returned", detail: "KMS verified caller has permissions" },
      { from: 1, to: 1, label: "Decrypt field data", detail: "Fernet(DEK).decrypt(ciphertext) → SSN" },
      { from: 1, to: 0, label: "✅ Decrypted PHI", detail: "Envelope encryption complete" },
      { from: 1, to: 3, label: "Rotate KEK", detail: "Create new KMS key, re-wrap DEKs" },
      { from: 3, to: 1, label: "DEKs re-encrypted", detail: "Data NEVER re-encrypted — only DEK re-wrap" },
      { from: 1, to: 0, label: "🔑 Key rotated!", detail: "Zero-downtime rotation complete" },
    ],
    durationInFrames: 390,
  },
];
