import { SequenceData } from "./SequenceDiagram";

export const LLD_SEQUENCES: SequenceData[] = [
  {
    id: "parking-lot-sequence",
    title: "Parking Lot",
    subtitle: "Entry → Spot Allocation → Ticket → Payment → Exit",
    actors: ["Driver", "Entry Kiosk", "Spot Allocator", "Payment Gateway"],
    steps: [
      { from: 0, to: 1, label: "Arrives at gate", detail: "ANPR scans license plate" },
      { from: 1, to: 2, label: "Find nearest spot", detail: "SELECT ... FOR UPDATE SKIP LOCKED" },
      { from: 2, to: 1, label: "Spot A-12 assigned", detail: "Floor 1, Compact" },
      { from: 1, to: 0, label: "Gate opens, ticket issued", detail: "TICK-000001" },
      { from: 0, to: 0, label: "Parks at spot A-12", detail: "Entry time recorded" },
      { from: 0, to: 1, label: "Returns for exit", detail: "Presents ticket / ANPR" },
      { from: 1, to: 3, label: "Calculate fee", detail: "3.5 hrs × $20/hr = $70" },
      { from: 3, to: 1, label: "Payment confirmed", detail: "Paid via card" },
      { from: 1, to: 0, label: "Gate opens, exit recorded", detail: "Spot A-12 → AVAILABLE" },
    ],
    durationInFrames: 270,
  },
  {
    id: "chess-game-sequence",
    title: "Chess Game",
    subtitle: "Player → Move → Validation → Board Update → Game State",
    actors: ["Player", "ChessEngine", "MoveValidator", "Board"],
    steps: [
      { from: 0, to: 1, label: "Submits move", detail: "e2 → e4" },
      { from: 1, to: 2, label: "Validate move", detail: "Check rules + legal moves" },
      { from: 2, to: 1, label: "Move is legal", detail: "Valid piece movement" },
      { from: 1, to: 3, label: "Update board state", detail: "Move piece on grid" },
      { from: 3, to: 1, label: "Board updated", detail: "New FEN position" },
      { from: 1, to: 2, label: "Check game status", detail: "Check/Checkmate/Stalemate?" },
      { from: 2, to: 1, label: "Game continues", detail: "Opponent's turn" },
      { from: 1, to: 0, label: "Display updated board", detail: "Show new position" },
    ],
    durationInFrames: 240,
  },
  {
    id: "tic-tac-toe-sequence",
    title: "Tic-Tac-Toe",
    subtitle: "Player → Move → Win Check → Board Update → Turn Switch",
    actors: ["Player", "Game Engine", "Win Detector", "Board"],
    steps: [
      { from: 0, to: 1, label: "Places X at (0,0)", detail: "Top-left corner" },
      { from: 1, to: 2, label: "Check win condition", detail: "3 in a row?" },
      { from: 2, to: 1, label: "No winner yet", detail: "Game continues" },
      { from: 1, to: 3, label: "Update board", detail: "Mark X at (0,0)" },
      { from: 3, to: 1, label: "Board updated", detail: "Turn switched" },
      { from: 0, to: 1, label: "Places O at (1,1)", detail: "Center" },
      { from: 1, to: 2, label: "Check win condition", detail: "3 in a row?" },
      { from: 2, to: 1, label: "No winner yet", detail: "Game continues" },
      { from: 0, to: 1, label: "Places X at (2,2)", detail: "Bottom-right diagonal" },
      { from: 1, to: 2, label: "Check win condition", detail: "Diagonal complete! (0,0)-(1,1)-(2,2)" },
      { from: 2, to: 1, label: "Player X wins!", detail: "Game over — restart?" },
      { from: 1, to: 0, label: "Display victory", detail: "X wins in 3 moves" },
    ],
    durationInFrames: 330,
  },
  {
    id: "snakes-and-ladders-sequence",
    title: "Snakes & Ladders",
    subtitle: "Roll → Move → Check → Snake/Ladder → Turn End",
    actors: ["Player", "Dice", "Board", "Game Engine"],
    steps: [
      { from: 0, to: 1, label: "Rolls dice", detail: "Press roll button" },
      { from: 1, to: 0, label: "Dice shows 4", detail: "🎲 Rolled a 4" },
      { from: 0, to: 2, label: "Move 4 spaces", detail: "Position: 12 → 16" },
      { from: 2, to: 3, label: "Check position 16", detail: "Bottom of ladder?" },
      { from: 3, to: 2, label: "Ladder found! 16→28", detail: "Climb up! 🪜" },
      { from: 2, to: 0, label: "New position: 28", detail: "Next player's turn" },
    ],
    durationInFrames: 180,
  },
  {
    id: "vending-machine-sequence",
    title: "Vending Machine",
    subtitle: "Insert Money → Select Item → Dispense → Change Return",
    actors: ["Customer", "VendingMachine", "Inventory", "PaymentModule"],
    steps: [
      { from: 0, to: 1, label: "Inserts $5 bill", detail: "Bill acceptor validates" },
      { from: 1, to: 3, label: "Credit: $5.00", detail: "Update balance" },
      { from: 3, to: 1, label: "Balance OK", detail: "Ready for selection" },
      { from: 0, to: 1, label: "Selects item B3", detail: "Chips — $1.50" },
      { from: 1, to: 2, label: "Check availability", detail: "Item B3: qty=8" },
      { from: 2, to: 1, label: "In stock", detail: "Sufficient quantity" },
      { from: 1, to: 3, label: "Deduct $1.50", detail: "Balance: $5.00 → $3.50" },
      { from: 3, to: 1, label: "Payment approved", detail: "Dispensing item" },
      { from: 1, to: 2, label: "Dispense item B3", detail: "Release from coil" },
      { from: 2, to: 1, label: "Item dispensed", detail: "Ready for pickup" },
      { from: 1, to: 0, label: "Open compartment", detail: "Take your chips" },
    ],
    durationInFrames: 300,
  },
  {
    id: "lru-cache-sequence",
    title: "LRU Cache",
    subtitle: "Get/Set → Eviction Check → Cache Update → Return",
    actors: ["Client", "LRUCache", "HashMap", "DoublyLinkedList"],
    steps: [
      { from: 0, to: 1, label: "GET('user:42')", detail: "Cache lookup" },
      { from: 1, to: 2, label: "Hash(key) → idx 7", detail: "O(1) lookup" },
      { from: 2, to: 1, label: "Found node", detail: "Cache HIT" },
      { from: 1, to: 3, label: "Move to head", detail: "Mark as recently used" },
      { from: 3, to: 1, label: "Node at head", detail: "LRU order updated" },
      { from: 1, to: 0, label: "Return: {name:'Alice'}", detail: "Cache HIT — 2ms" },
      { from: 0, to: 1, label: "SET('user:99', data)", detail: "Cache write" },
      { from: 1, to: 3, label: "Add to head", detail: "New node inserted" },
      { from: 3, to: 1, label: "Capacity exceeded", detail: "Need to evict" },
      { from: 1, to: 3, label: "Remove tail node", detail: "Evicts 'user:01'" },
      { from: 1, to: 0, label: "Written: OK", detail: "Cache write complete" },
    ],
    durationInFrames: 300,
  },
  {
    id: "rate-limiter-sequence",
    title: "Rate Limiter",
    subtitle: "Request → Token Check → Allow/Block → Response",
    actors: ["Client", "RateLimiter", "TokenBucket", "API Server"],
    steps: [
      { from: 0, to: 1, label: "HTTP POST /api/data", detail: "Request arrives" },
      { from: 1, to: 2, label: "Consume token", detail: "Check bucket" },
      { from: 2, to: 1, label: "Token available", detail: "10 tokens remaining" },
      { from: 1, to: 3, label: "Forward request", detail: "Proceed to handler" },
      { from: 3, to: 1, label: "200 OK response", detail: "Request fulfilled" },
      { from: 1, to: 0, label: "200 OK", detail: "Served within limits" },
      { from: 0, to: 1, label: "HTTP POST /api/data", detail: "15th request in window" },
      { from: 1, to: 2, label: "Consume token", detail: "Bucket empty!" },
      { from: 2, to: 1, label: "RATE LIMITED", detail: "0 tokens — THROTTLED" },
      { from: 1, to: 0, label: "429 Too Many Requests", detail: "Retry-After: 30s" },
    ],
    durationInFrames: 270,
  },
  {
    id: "pub-sub-sequence",
    title: "Pub-Sub System",
    subtitle: "Publisher → Topics → Subscribers → Message Delivery",
    actors: ["Publisher", "Topic", "Subscription", "Subscriber"],
    steps: [
      { from: 0, to: 1, label: "Publish: 'order.created'", detail: "Message: {order_id: 123}" },
      { from: 1, to: 2, label: "Match subscribers", detail: "3 subscribers found" },
      { from: 2, to: 3, label: "Deliver message", detail: "Subscriber A: push" },
      { from: 2, to: 3, label: "Deliver message", detail: "Subscriber B: email" },
      { from: 2, to: 3, label: "Deliver message", detail: "Subscriber C: webhook" },
      { from: 3, to: 2, label: "ACK received", detail: "All 3 delivered" },
      { from: 2, to: 1, label: "All acknowledged", detail: "Ready for next message" },
      { from: 1, to: 0, label: "Publish confirmed", detail: "Offset: 42" },
    ],
    durationInFrames: 240,
  },
  {
    id: "movie-ticket-sequence",
    title: "Movie Ticket Booking",
    subtitle: "Search → Select → Reserve → Payment → Confirm",
    actors: ["User", "MovieService", "SeatAllocator", "PaymentService"],
    steps: [
      { from: 0, to: 1, label: "Search: 'Inception'", detail: "Showtimes for today" },
      { from: 1, to: 0, label: "Screen 3, 7:30 PM", detail: "12 seats available" },
      { from: 0, to: 2, label: "Select: D4, D5, D6", detail: "3 seats together" },
      { from: 2, to: 1, label: "Reserve seats", detail: "Hold for 10 minutes" },
      { from: 1, to: 0, label: "₹750 — Confirm?", detail: "₹250 × 3 seats" },
      { from: 0, to: 3, label: "Process payment", detail: "Credit card" },
      { from: 3, to: 1, label: "Payment confirmed", detail: "TXN: PAY-98765" },
      { from: 1, to: 2, label: "Lock seats permanently", detail: "D4, D5, D6 → BOOKED" },
      { from: 2, to: 1, label: "Seats locked", detail: "Booking confirmed" },
      { from: 1, to: 0, label: "✅ Tickets booked!", detail: "SMS + Email sent" },
    ],
    durationInFrames: 270,
  },
  {
    id: "splitwise-sequence",
    title: "Splitwise (Expense Sharing)",
    subtitle: "Add → Split → Balance Update → Settlement",
    actors: ["User", "SplitwiseService", "ExpenseManager", "BalanceLedger"],
    steps: [
      { from: 0, to: 1, label: "Add expense: Dinner $60", detail: "Paid by Alice" },
      { from: 1, to: 2, label: "Split equally", detail: "Alice, Bob, Charlie" },
      { from: 2, to: 3, label: "Alice: +$60", detail: "Paid amount credit" },
      { from: 2, to: 3, label: "Bob: -$20", detail: "Owes $20" },
      { from: 2, to: 3, label: "Charlie: -$20", detail: "Owes $20" },
      { from: 3, to: 1, label: "Balances updated", detail: "New net positions" },
      { from: 1, to: 0, label: "Expense recorded", detail: "Bob owes Alice $20" },
      { from: 0, to: 1, label: "Settle up: Bob→Alice", detail: "$20 payment" },
      { from: 1, to: 3, label: "Update balances", detail: "Reduce Bob's debt" },
      { from: 3, to: 1, label: "Settled: $0", detail: "All square" },
      { from: 1, to: 0, label: "✅ Settled up!", detail: "Net owed: $0" },
    ],
    durationInFrames: 300,
  },
  {
    id: "cab-booking-sequence",
    title: "Cab Booking (Uber)",
    subtitle: "Request → Geo Matching → Dispatch → Trip → Kafka Pipeline",
    actors: ["Rider", "Rider Service", "Driver Service", "Geo Index", "Kafka"],
    steps: [
      { from: 0, to: 1, label: "Request ride", detail: "Pickup: King's Circle" },
      { from: 1, to: 2, label: "Find nearby drivers", detail: "GEORADIUS pickup 3km" },
      { from: 2, to: 3, label: "Geo-radius search", detail: "Redis GEO query" },
      { from: 3, to: 2, label: "Top 5 drivers", detail: "Sorted by distance ASC" },
      { from: 2, to: 0, label: "Driver: Rahul (2.1km)", detail: "Mini — ETA 5 min" },
      { from: 0, to: 2, label: "Accept driver", detail: "Confirm booking" },
      { from: 2, to: 1, label: "Dispatch confirmed", detail: "Driver notified" },
      { from: 1, to: 4, label: "Publish trip event", detail: "Kafka topic: trip.events" },
      { from: 4, to: 1, label: "Event acknowledged", detail: "Offset: 1289" },
      { from: 1, to: 0, label: "✅ Trip created!", detail: "T-1A2B3C4D — $12.50" },
    ],
    durationInFrames: 270,
  },
  {
    id: "library-management-sequence",
    title: "Library Management",
    subtitle: "Search → Borrow → Return → Fine Calculation",
    actors: ["Member", "Catalog", "LendingService", "FineCalculator"],
    steps: [
      { from: 0, to: 1, label: "Search: 'Clean Code'", detail: "Full-text search" },
      { from: 1, to: 0, label: "3 copies available", detail: "Section A, Row 3" },
      { from: 0, to: 2, label: "Borrow 'Clean Code'", detail: "ISBN: 978-0-13-468599-1" },
      { from: 2, to: 1, label: "Check availability", detail: "available_copies > 0" },
      { from: 1, to: 2, label: "Available: decrement", detail: "3 → 2 copies left" },
      { from: 2, to: 0, label: "Book issued", detail: "Due: 14 days" },
      { from: 0, to: 2, label: "Return book", detail: "5 days overdue" },
      { from: 2, to: 3, label: "Calculate fine", detail: "5 days × $1/day = $5" },
      { from: 3, to: 2, label: "Fine: $5.00", detail: "Progressive rate" },
      { from: 2, to: 0, label: "Book returned", detail: "Fine: $5.00 — pay now?" },
    ],
    durationInFrames: 270,
  },
  {
    id: "car-rental-sequence",
    title: "Car Rental",
    subtitle: "Search → Book → Pickup → Return → Payment",
    actors: ["Customer", "SearchService", "BookingService", "PaymentService"],
    steps: [
      { from: 0, to: 1, label: "Search: Sedan, 3 days", detail: "Mumbai, Dec 20-22" },
      { from: 1, to: 0, label: "Honda City: $180", detail: "$60/day × 3 days" },
      { from: 0, to: 2, label: "Book Honda City", detail: "License: MH-01-AB-1234" },
      { from: 2, to: 0, label: "Reservation confirmed", detail: "Booking ID: BR-78901" },
      { from: 0, to: 2, label: "Pickup car", detail: "Odometer: 15,234 km" },
      { from: 2, to: 0, label: "Trip started", detail: "Fuel: Full tank" },
      { from: 0, to: 2, label: "Return car", detail: "Odometer: 15,640 km" },
      { from: 2, to: 3, label: "Calculate charges", detail: "406 km × $0.14/km = $56.84" },
      { from: 3, to: 2, label: "Total: $236.84", detail: "Base + distance + tax" },
      { from: 2, to: 3, label: "Process payment", detail: "Card ending in 4242" },
      { from: 3, to: 0, label: "✅ Paid & returned!", detail: "Receipt emailed" },
    ],
    durationInFrames: 300,
  },
  {
    id: "atm-banking-sequence",
    title: "ATM Banking",
    subtitle: "Insert Card → PIN → Select → Withdraw → Cash + Receipt",
    actors: ["Customer", "ATM", "BankServer", "CashDispenser"],
    steps: [
      { from: 0, to: 1, label: "Inserts card", detail: "Card number: ****-****-4242" },
      { from: 1, to: 2, label: "Validate card", detail: "Check issuer, expiry" },
      { from: 2, to: 1, label: "Card valid", detail: "Prompt for PIN" },
      { from: 1, to: 0, label: "Enter PIN", detail: "Secure PIN pad" },
      { from: 0, to: 1, label: "PIN entered (****)", detail: "Encrypted transmission" },
      { from: 1, to: 2, label: "Verify PIN + balance", detail: "HSM decrypt + compare" },
      { from: 2, to: 1, label: "Balance: $5,200", detail: "Select withdrawal amount" },
      { from: 0, to: 1, label: "Withdraw $200", detail: "From checking" },
      { from: 1, to: 2, label: "Authorize $200 debit", detail: "Idempotency key" },
      { from: 2, to: 1, label: "Transaction approved", detail: "TXID: ATM-98765" },
      { from: 1, to: 3, label: "Dispense $200", detail: "10 × $20 bills" },
      { from: 3, to: 1, label: "Cash dispensed", detail: "Printing receipt" },
      { from: 1, to: 0, label: "✅ Take cash + receipt", detail: "Balance: $5,000" },
    ],
    durationInFrames: 360,
  },
  {
    id: "inventory-management-sequence",
    title: "Inventory Management",
    subtitle: "Order → Stock Check → Allocate → Ship → Update",
    actors: ["Customer", "OrderService", "InventoryService", "Warehouse"],
    steps: [
      { from: 0, to: 1, label: "Place order: iPhone 15", detail: "Qty: 2" },
      { from: 1, to: 2, label: "Check stock", detail: "Warehouse A, B, C" },
      { from: 2, to: 1, label: "Stock: 15 units", detail: "Allocate from warehouse A" },
      { from: 1, to: 3, label: "Reserve 2 units", detail: "SKU: APL-IP15-128" },
      { from: 3, to: 1, label: "Reserved: WH-A, Rack 4", detail: "Update inventory count" },
      { from: 1, to: 0, label: "Order confirmed", detail: "Estimated delivery: 2 days" },
      { from: 1, to: 3, label: "Ship order", detail: "Pick + pack + ship" },
      { from: 3, to: 1, label: "Shipped: AWB-123456", detail: "Tracking ID generated" },
      { from: 1, to: 0, label: "📦 Shipped!", detail: "Tracking link sent" },
    ],
    durationInFrames: 240,
  },
  {
    id: "payment-processing-sequence",
    title: "Payment Processing",
    subtitle: "Validate → Fraud Check → Gateway → Complete → Refund",
    actors: ["Customer", "PaymentService", "FraudDetector", "PaymentGateway"],
    steps: [
      { from: 0, to: 1, label: "Pay $1,500", detail: "For MacBook Pro" },
      { from: 1, to: 1, label: "Run validators", detail: "Amount OK, Currency OK" },
      { from: 1, to: 2, label: "Fraud check", detail: "Amount threshold check" },
      { from: 2, to: 1, label: "Legitimate", detail: "Velocity check passed" },
      { from: 1, to: 3, label: "Charge $1,500", detail: "Via Stripe gateway" },
      { from: 3, to: 1, label: "Charged: TXN-ch_123", detail: "Stripe charge ID" },
      { from: 1, to: 0, label: "✅ Payment completed!", detail: "Fee: $37.50 (2.5%)" },
      { from: 0, to: 1, label: "Request refund $500", detail: "Damaged item" },
      { from: 1, to: 3, label: "Refund $500", detail: "Partial refund" },
      { from: 3, to: 1, label: "Refunded: RF-abc123", detail: "Payment status: PARTIALLY_REFUNDED" },
      { from: 1, to: 0, label: "✅ $500 refunded", detail: "Refund processed" },
    ],
    durationInFrames: 300,
  },
  {
    id: "job-scheduling-sequence",
    title: "Job Scheduling",
    subtitle: "Submit → Queue → Schedule → Execute → Complete",
    actors: ["Client", "Scheduler", "JobQueue", "Worker"],
    steps: [
      { from: 0, to: 1, label: "Submit job: data_pipeline", detail: "Priority: HIGH" },
      { from: 1, to: 2, label: "Enqueue job", detail: "Persist to DB + Redis" },
      { from: 2, to: 1, label: "Queued: offset 42", detail: "Job ID: JOB-12345" },
      { from: 1, to: 0, label: "Job accepted", detail: "Scheduled for execution" },
      { from: 1, to: 2, label: "Poll next job", detail: "Dequeue with priority" },
      { from: 2, to: 3, label: "Dispatch job", detail: "Round-robin worker assignment" },
      { from: 3, to: 3, label: "Execute job", detail: "Running: data_pipeline" },
      { from: 3, to: 2, label: "Job completed", detail: "Output: success (2.3s)" },
      { from: 2, to: 1, label: "Mark as done", detail: "Update job status" },
      { from: 1, to: 0, label: "✅ Job completed!", detail: "Duration: 2.3s, Status: SUCCESS" },
    ],
    durationInFrames: 270,
  },
  {
    id: "notification-service-sequence",
    title: "Notification Service",
    subtitle: "Submit → Queue → Workers → Channel Delivery → Status",
    actors: ["Client", "Orchestrator", "MessageQueue", "ChannelWorker"],
    steps: [
      { from: 0, to: 1, label: "Send: Welcome email", detail: "Template: welcome_email" },
      { from: 1, to: 1, label: "Idempotency check", detail: "Key: notif_welcome_123" },
      { from: 1, to: 2, label: "Enqueue messages", detail: "3 recipients, 1 channel" },
      { from: 2, to: 3, label: "Dequeue: batch", detail: "Rate: 50/sec (token bucket)" },
      { from: 3, to: 3, label: "Send via SES", detail: "Email provider: Amazon SES" },
      { from: 3, to: 2, label: "Status: SENT", detail: "Provider ID: ses_abc123" },
      { from: 2, to: 1, label: "Message delivered", detail: "All 3 sent successfully" },
      { from: 1, to: 0, label: "✅ Notification sent!", detail: "3/3 delivered, cost: $0.0003" },
    ],
    durationInFrames: 240,
  },
  {
    id: "search-platform-sequence",
    title: "Search Platform",
    subtitle: "Query → Parse → Index Search → Rank → Results",
    actors: ["User", "QueryParser", "SearchIndex", "Ranker"],
    steps: [
      { from: 0, to: 1, label: "Search: 'best pizza'", detail: "Natural language query" },
      { from: 1, to: 1, label: "Parse & analyze", detail: "Tokenize, stem, expand" },
      { from: 1, to: 2, label: "Query inverted index", detail: "pizza → doc IDs [3, 7, 12, 45]" },
      { from: 2, to: 3, label: "Rank results", detail: "TF-IDF score + freshness boost" },
      { from: 3, to: 1, label: "Top 10 results", detail: "Scores: [0.92, 0.87, 0.76, ...]" },
      { from: 1, to: 0, label: "📊 247 results in 0.3s", detail: "Joe's Pizza (4.8★) — 0.3km" },
    ],
    durationInFrames: 210,
  },
];
